### ISSUE TITLE
After updating to 1.0 the node_map does not find the specified features

### ISSUE THREAD

**Issue by wuyuanyi135** [genicam/harvesters#107]
**Describe the bug**
In my old code base, the code execute normally
```python
    def reload_camera_driver(self):
        node = self.acquirer.device.node_map
        node.LineSelector.value = 'Line1'
        node.LineMode.value = 'Output'
        node.LineInverter.value = True
        node.LineSource.value = "ExposureActive"
        node.ExposureTime.value = 45.0
        node.AcquisitionFrameRateMode.value = "Basic"
        node.AcquisitionFrameRate.value = self.config[SECTION]["fps"]
```

After updating the 1.0.1, the following exception occurs
```
Traceback (most recent call last):
  File "C:\Users\wuyua\PycharmProjects\RxExperiments\venv\lib\site-packages\genicam\genapi.py", line 2080, in __getattr__
    return self.get_node(attribute)
  File "C:\Users\wuyua\PycharmProjects\RxExperiments\venv\lib\site-packages\genicam\genapi.py", line 2032, in get_node
    return _genapi.NodeMap_get_node(self, key)
_genapi.LogicalErrorException: Node not existing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\wuyua\PycharmProjects\RxExperiments\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-85f470d12a85>", line 1, in <module>
    node.Height
  File "C:\Users\wuyua\PycharmProjects\RxExperiments\venv\lib\site-packages\genicam\genapi.py", line 2084, in __getattr__
    raise AttributeError from e
AttributeError
Traceback (most recent call last):
  File "C:\Users\wuyua\PycharmProjects\RxExperiments\venv\lib\site-packages\genicam\genapi.py", line 2080, in __getattr__
    return self.get_node(attribute)
  File "C:\Users\wuyua\PycharmProjects\RxExperiments\venv\lib\site-packages\genicam\genapi.py", line 2032, in get_node
    return _genapi.NodeMap_get_node(self, key)
_genapi.LogicalErrorException: Node not existing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\wuyua\PycharmProjects\RxExperiments\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-c3660f52aec1>", line 1, in <module>
    node.height
  File "C:\Users\wuyua\PycharmProjects\RxExperiments\venv\lib\site-packages\genicam\genapi.py", line 2084, in __getattr__
    raise AttributeError from e
AttributeError
```
**To Reproduce**
Upgrade version from 0.x to 1.x

**Expected behavior**
The node map should be configured as previous version

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python: 3.7.6
 - Harvester: 1.0.1 (not working) 0.2.13 (working)
 - GenTL Producer: MATRIX VISION
 - Camera: AV U051

**Comment by kazunarikudo** [comment]
@wuyuanyi135 Hi. Thank you for the report. Excuse me, does the node map really have a node called literally `height` but not `Height`? /Kazunari

**Comment by wuyuanyi135** [comment]
@kazunarikudo No. The case does not help. I tried many different cases but it still gave the same error. I think the feature name should not change given the GenTL compliant drivers. I tried to list the attributes of the node map: 
```
['DeviceAccessStatus',
 'DeviceControl',
 'DeviceDisplayName',
 'DeviceEndianessMechanism',
 'DeviceFamilyName',
 'DeviceID',
 'DeviceInformation',
 'DeviceManufacturerInfo',
 'DeviceModelName',
 'DeviceSerialNumber',
 'DeviceTimestampFrequency',
 'DeviceType',
 'DeviceUserID',
 'DeviceVendorName',
 'DeviceVersion',
 'GenCPVersionMajor',
 'GenCPVersionMinor',
 'GevDeviceGateway',
 'GevDeviceIPAddress',
 'GevDeviceMACAddress',
 'GevDeviceSubnetMask',
 'GevVersionMajor',
 'GevVersionMinor',
 'LinkCommandRetryCount',
 'LinkCommandTimeout',
 'Root',
 'StreamEnumeration',
 'StreamID',
 'StreamSelector',
 'U3vVersionMajor',
 'U3vVersionMinor',
 '__class__',
 '__del__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__swig_destroy__',
 '__swig_getmethods__',
 '__swig_setmethods__',
 '__weakref__',
 '_concrete_port',
 '_connect',
 '_destroy',
 '_get_device_info',
 '_get_device_name',
 '_get_node',
 '_get_nodes',
 '_invalidate_nodes',
 'clear_xml_cache',
 'connect',
 'device_info',
 'disconnect',
 'get_node',
 'has_node',
 'load_xml_from_file',
 'load_xml_from_string',
 'load_xml_from_zip_file',
 'nodes',
 'pointer',
 'poll',
 'this']
```

**Comment by kazunarikudo** [comment]
Hi. So do you mean the following nodes are missing as long as you try with version 1.x?
```
LineSelector
LineMode
LineInverter
LineSource
ExposureTime
AcquisitionFrameRateMode
AcquisitionFrameRate
```
One more thing, could you tell me why did you excerpt the following message? I would like to see the message that you get when you try to access the `Height` node.
```
Traceback (most recent call last):
  File "C:\Users\wuyua\PycharmProjects\RxExperiments\venv\lib\site-packages\genicam\genapi.py", line 2080, in __getattr__
    return self.get_node(attribute)
  File "C:\Users\wuyua\PycharmProjects\RxExperiments\venv\lib\site-packages\genicam\genapi.py", line 2032, in get_node
    return _genapi.NodeMap_get_node(self, key)
_genapi.LogicalErrorException: Node not existing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\wuyua\PycharmProjects\RxExperiments\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-85f470d12a85>", line 1, in <module>
    node.Height
  File "C:\Users\wuyua\PycharmProjects\RxExperiments\venv\lib\site-packages\genicam\genapi.py", line 2084, in __getattr__
    raise AttributeError from e
AttributeError
Traceback (most recent call last):
  File "C:\Users\wuyua\PycharmProjects\RxExperiments\venv\lib\site-packages\genicam\genapi.py", line 2080, in __getattr__
    return self.get_node(attribute)
  File "C:\Users\wuyua\PycharmProjects\RxExperiments\venv\lib\site-packages\genicam\genapi.py", line 2032, in get_node
    return _genapi.NodeMap_get_node(self, key)
_genapi.LogicalErrorException: Node not existing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\wuyua\PycharmProjects\RxExperiments\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-c3660f52aec1>", line 1, in <module>
    node.height
  File "C:\Users\wuyua\PycharmProjects\RxExperiments\venv\lib\site-packages\genicam\genapi.py", line 2084, in __getattr__
    raise AttributeError from e
AttributeError
```

**Comment by wuyuanyi135** [comment]
@kazunarikudo Oops! I must have copied the wrong stacktrace when I was trying out the example code. The following is the actual stacktrace I got. Sorry for the confusion. Also, the `Height` node is also missing. That's what I can tell after running the example code.
```
Traceback (most recent call last):
  File "C:\Users\wuyua\PycharmProjects\CommandCenter\env\lib\site-packages\genicam\genapi.py", line 2080, in __getattr__
    return self.get_node(attribute)
  File "C:\Users\wuyua\PycharmProjects\CommandCenter\env\lib\site-packages\genicam\genapi.py", line 2032, in get_node
    return _genapi.NodeMap_get_node(self, key)
_genapi.LogicalErrorException: Node not existing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\wuyua\PycharmProjects\CommandCenter\widgets\Menus.py", line 101, in connectImageSource
    image_source.start()
  File "C:\Users\wuyua\PycharmProjects\CommandCenter\services\image_sources.py", line 180, in start
    self.reload_camera_driver()
  File "C:\Users\wuyua\PycharmProjects\CommandCenter\services\image_sources.py", line 169, in reload_camera_driver
    node.LineSelector.value = 'Line1'
  File "C:\Users\wuyua\PycharmProjects\CommandCenter\env\lib\site-packages\genicam\genapi.py", line 2084, in __getattr__
    raise AttributeError from e
AttributeError
```

**Comment by wuyuanyi135** [comment]
Also, in `0.2.17`, run `dir(node_map)` I could get the feature list 
```
['AcquisitionAbort', 'AcquisitionArm', 'AcquisitionControl', 'AcquisitionFrameCount', 'AcquisitionFrameRate', 'AcquisitionFrameRateMode', 'AcquisitionMode', 'AcquisitionStart', 'AcquisitionStatus', 'AcquisitionStatusSelector', 'AcquisitionStop', 'AnalogControl', 'BalanceRatio', 'BalanceRatioSelector', 'BinningHorizontal', 'BinningHorizontalMode', 'BinningSelector', 'BinningVertical', 'BinningVerticalMode', 'BlackLevel', 'BlackLevelSelector', 'ColorTransformationControl', 'ColorTransformationEnable', 'ColorTransformationSelector', 'ColorTransformationValue', 'ColorTransformationValueSelector', 'CorrectionControl', 'CorrectionDataSize', 'CorrectionEntryType', 'CorrectionInfo', 'CorrectionMode', 'CorrectionSelector', 'CorrectionSetDefault', 'CorrectionSetSelector', 'DecimationHorizontal', 'DecimationHorizontalMode', 'DecimationVertical', 'DecimationVerticalMode', 'DeviceControl', 'DeviceFamilyName', 'DeviceFirmwareID', 'DeviceFirmwareIDSelector', 'DeviceFirmwareUploadType', 'DeviceFirmwareVersion', 'DeviceFirmwareVersionSelector', 'DeviceGenCPVersionMajor', 'DeviceGenCPVersionMinor', 'DeviceIndicatorMode', 'DeviceLinkThroughputLimit', 'DeviceLinkThroughputLimitMode', 'DeviceManufacturerInfo', 'DeviceModelName', 'DeviceReset', 'DeviceSFNCVersionMajor', 'DeviceSFNCVersionMinor', 'DeviceSFNCVersionSubMinor', 'DeviceScanType', 'DeviceSerialNumber', 'DeviceTemperature', 'DeviceTemperatureSelector', 'DeviceUserID', 'DeviceVendorName', 'DeviceVersion', 'DigitalIOControl', 'ExposureMode', 'ExposureTime', 'FileAccessBuffer', 'FileAccessControl', 'FileAccessLength', 'FileAccessOffset', 'FileOpenMode', 'FileOperationExecute', 'FileOperationResult', 'FileOperationSelector', 'FileOperationStatus', 'FileProcessStatus', 'FileSelector', 'FileSize', 'FileStatus', 'Gain', 'GainSelector', 'Gamma', 'Height', 'HeightMax', 'Hue', 'ImageFormatControl', 'InputDebounceMode', 'InputDebounceTime', 'LineInverter', 'LineMode', 'LineSelector', 'LineSource', 'LineStatus', 'OffsetX', 'OffsetY', 'OutputDurationMode', 'OutputDurationTime', 'PayloadSize', 'PixelColorFilter', 'PixelFormat', 'PixelSize', 'ReverseX', 'Root', 'Saturation', 'SensorHeight', 'SensorWidth', 'TestControl', 'TestPendingAck', 'Timestamp', 'TransportLayerControl', 'TriggerActivation', 'TriggerDelay', 'TriggerMode', 'TriggerSelector', 'TriggerSoftware', 'TriggerSource', 'UserOutputSelector', 'UserOutputValue', 'UserSetControl', 'UserSetDefault', 'UserSetLoad', 'UserSetSave', 'UserSetSelector', 'Width', 'WidthMax', '__class__', '__del__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__swig_destroy__', '__swig_getmethods__', '__swig_setmethods__', '__weakref__', '_concrete_port', '_connect', '_destroy', '_get_device_info', '_get_device_name', '_invalidate_nodes', 'clear_xml_cache', 'connect', 'device_info', 'disconnect', 'get_node', 'get_nodes', 'load_xml_from_file', 'load_xml_from_string', 'load_xml_from_zip_file', 'pointer', 'poll', 'this']
```

**Comment by wuyuanyi135** [comment]
It was very strange. I could confirm the versions work
* 0.2.17 and prior
* 0.2.18 (not available from pypi, installed by git+tag)
and after version 1.0.0, the problem emerges.

Weird enough, I even tried the commit 057dbafd578c1d53d117bda6f4debb65041cdf5e and it **does work**. I don't think there is any change in the code base in version 1.0.0 but something broke magically?

**Comment by kazunarikudo** [comment]
@wuyuanyi135 Thank you for the update. It's interesting to hear that 0.2.18 reproduces the phenomenon. It's very early to conclude but 0.2s rely on the beta version of GenICam Python binding so-called `genicam2` and 1.0s rely on the official version so-called `genicam`. One guess I have is the node visibility might be dynamically changed while you are running your code because the hidden nodes look to be grouped in a logical class. The visibility can be changed by the combination between the camera description XML file and your codebase. It might be better to look at the XML file...

**Comment by kazunarikudo** [comment]
@wuyuanyi135 Okay, so could you confirm if the missing nodes are always missing or not, please?

**Comment by kazunarikudo** [comment]
@wuyuanyi135 One more request: Could you tell me (1) the model name and (3) the manufacturer name of the camera, please?

**Comment by wuyuanyi135** [comment]
@kazunarikudo It is an Allied Vision Mako U051 camera.
And yes they are always missing as long as I am using the version 1.x.x.

**Comment by kazunarikudo** [comment]
@wuyuanyi135 Thank you. So how about 0.2.18?

**Comment by kazunarikudo** [comment]
And could list up the missing nodes? I know it’s abut annoying but please!

**Comment by kazunarikudo** [comment]
And could you provide me the camera XML file following to the instructions described as follows? https://github.com/genicam/harvesters/wiki/FAQ#id-like-to-store-the-downloaded-xmlzip-file-how-can-i-do-that

**Comment by kazunarikudo** [comment]
This is just for your information but I have just uploaded version 0.2.18 to PyPI.

**Comment by kazunarikudo** [comment]
Maybe I just nailed the suspect. Long story short, if you want to access the feature nodes that the camera, you have to code as follows:
```
node_map = self.acquirer.remote_device.node_map
```
Instead of:
```
node_map = self.acquirer.device.node_map
```
An `ImageAcquirer` node has two properties, `remote_device` and `device`, but note that they are not identical. The former one is the camera, a physical device, itself but the latter one is a proxy of the remote device that the GenTL standard defines and it offers a GenTL consumer only the GenTL relevant features that help him to create a DataStream module.

In the early days, Harvester implemented the remote device as the `device` property and there was no way to communicate with GenTL's device module but having learned the difference I introduced both `device` and `remote_device` at version 0.2.12 creating ticket #84.

Please let me know if the change above makes a difference.

**Comment by wuyuanyi135** [comment]
@kazunarikudo Thanks for your update! will try `remote_device` out when I get to lab.

**Comment by kazunarikudo** [comment]
@wuyuanyi135 I believe it works for you! (Some people simultaneously reported a similar phenomenon so I fell in a panic yesterday, to be honest...)

**Comment by kazunarikudo** [comment]
NOTE: This ticket is waiting for a reply from the original reporter.

**Comment by axil** [comment]
That's not really intuitive, but it helps!
