### ISSUE TITLE
AcquisitionMode cannot set to MultiFrame

### ISSUE THREAD

**Issue by MomoHsieh** [genicam/harvesters#123]
**Describe the bug**

use harvesters to capture multi-frame
```
h = Harvester()
    h.add_cti_file(.../pylon-5.0.12.11829-x86_64/pylonSDK-5.0.12.11829-x86_64/pylon5/lib64/gentlproducer/gtl/ProducerU3V.cti')
    h.update_device_info_list()
    print(len(h.device_info_list))
    print(h.device_info_list[0])
    ia = h.create_image_acquirer(0)
    ia.remote_device.node_map.AcquisitionMode.value = 'MultiFrame'
    print(ia.remote_device.node_map.AcquisitionMode.value)
    print(dir(ia.remote_device.node_map.AcquisitionMode))
    ia.remote_device.node_map.Width.value = 300
    ia.remote_device.node_map.Height.value = 300
    ia.remote_device.node_map.PixelFormat.value = 'Mono8'
    ia.start_image_acquisition()
```
and bug is 

`Feature` 'AcquisitionMode' : cannot convert value 'MultiFrame', the value is invalid.`

```
(id_='Basler acA2440-75um (22957467)', vendor='Basler', model='acA2440-75um', tl_type='U3V', user_defined_name=None, serial_number='22957467', version='Unknown')
Traceback (most recent call last):
  File "harvester.py", line 19, in <module>
    ia.remote_device.node_map.AcquisitionMode.value = 'MultiFrame'
  File "/home/momo/.local/lib/python3.6/site-packages/genicam/genapi.py", line 2484, in <lambda>
    __setattr__ = lambda self, name, value: _swig_setattr(self, IEnumeration, name, value)
  File "/home/momo/.local/lib/python3.6/site-packages/genicam/genapi.py", line 101, in _swig_setattr
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)
  File "/home/momo/.local/lib/python3.6/site-packages/genicam/genapi.py", line 93, in _swig_setattr_nondynamic
    object.__setattr__(self, name, value)
  File "/home/momo/.local/lib/python3.6/site-packages/genicam/genapi.py", line 2531, in _set_value
    self._primal_set_value(value)
  File "/home/momo/.local/lib/python3.6/site-packages/genicam/genapi.py", line 2522, in _primal_set_value
    return _genapi.IEnumeration__primal_set_value(self, entry, verify)
_genapi.InvalidArgumentException: Feature 'AcquisitionMode' : cannot convert value 'MultiFrame', the value is invalid. : InvalidArgumentException thrown in node 'AcquisitionMode' while calling 'AcquisitionMode.FromString()' (file 'Enumeration.cpp', line 134)
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Python: 3.6.9
 - Harvester: harvesters==1.0.4
 - GenTL Producers = Pylon
 - Camera: Basler acA2440-75um

**Additional context**

I can set AcquisitionMode to  `SingleFrame` and `Continuous`

```
(id_='Basler acA2440-75um (22957467)', vendor='Basler', model='acA2440-75um', tl_type='U3V', user_defined_name=None, serial_number='22957467', version='Unknown')
300 x 300, Mono8, 90000 elements,
[1 1 1 ... 1 1 1]
[300 x 300, Mono8, 90000 elements,
[1 1 1 ... 1 1 1]]
1D: [1 1 1 ... 1 1 1]
2D: [[1 1 1 ... 2 2 2]
 [1 1 1 ... 2 1 2]
 [1 1 1 ... 2 1 2]
 ...
 [0 0 1 ... 1 1 2]
 [0 0 1 ... 2 1 2]
 [0 0 1 ... 1 1 1]]
```
Please help to solve this, thanks.

**Comment by kazunarikudo** [comment]
@MomoHsieh Hi, thank you for trying out Harvester. I have something that I would like to ask you. As the first step, could you give me the output of the following code?
```
print(ia.remote_device.node_map.AcquisitionMode.symbolics)
```
Thanks,
Kazunari

**Comment by MomoHsieh** [comment]
I just tried and got ('SingleFrame', 'Continuous')

![Kazam_screenshot_00003](https://user-images.githubusercontent.com/16541945/76069824-6e7fea80-5fce-11ea-949b-266f0ee26ebf.png)

**Comment by kazunarikudo** [comment]
Wow, it does not support `MultiFrame`. That's why you can set that.

**Comment by MomoHsieh** [comment]
So, if I want to get multiple frames, I need to set "Continuous" and  count frame which I want, right?
Like
```
while count < 30:
    with ia.fetch_buffer() as buffer:
            # Let's create an alias of the 2D image component:
            print(buffer)
            component = buffer.payload.components[0]
            print(buffer.payload.components)
            # Note that the number of components can be vary. If your
            # target remote device transmits a multi-part information, then
            # you'd get two or more components in the payload. However, now
            # we're working with a remote device that transmits only a 2D image.
            # So we manipulate only index 0 of the list object, components.
            
            # Let's see the acquired data in 1D:
            _1d = component.data
            print('1D: {0}'.format(_1d))
    count += 1
```

**Comment by kazunarikudo** [comment]
@MomoHsieh "Yes" would be an answer but you should understand that you will drop consecutive images until you call the `fetch_buffer` method because the camera itself continues to take images if the cycle is faster than another cycle for the method call. Do you use a hardware/software trigger to let the camera takes an image turning `TriggerMode` on? If so, your worry will go away because you know when the triggered timing. As far as I hear your comment, it'd be better to go on either way: (1) Use a camera that supports `MultiFrame` or (2) Use a hardware/software trigger to let the camera take an image.

**Comment by MomoHsieh** [comment]
@kazunarikudo I will use hardware/software trigger. Thanks a lot and you can close it.

**Comment by kazunarikudo** [comment]
@MomoHsieh Okay, good luck! /Kazunari
