### ISSUE TITLE
Loads of errors when stopping acquisition

### ISSUE THREAD

**Issue by bobcorn** [genicam/harvesters#139]
**Introduction**
Hi @kazunarikudo, this is the second issue I open, and I apologize for the inconvenience, but since it's related to another problem, I tought it was cleaner and clearer to talk about it in a new one.

**Describe the bug**
When ending my acquisition session calling the following code:

```
image_acquirer.stop_acquisition()
image_acquirer.destroy()
harvester.reset()
```

in order to stop acquisition and "shutdown" things, a series of errors raise to me. The traceback is:

```
Traceback (most recent call last):
  File "issue.py", line 189, in <module>
    run()
  File "issue.py", line 180, in run
    shutdown_camera(ia, h)
  File "issue.py", line 69, in shutdown_camera
    image_acquirer.stop_acquisition()
  File "C:\Users\rossinim\AppData\Roaming\Python\Python37\site-packages\harvesters-_issue_130-py3.7.egg\harvesters\core.py", line 2338, in stop_acquisition
    self._release_buffers()
  File "C:\Users\rossinim\AppData\Roaming\Python\Python37\site-packages\harvesters-_issue_130-py3.7.egg\harvesters\core.py", line 2400, in _release_buffers
    _ = data_stream.revoke_buffer(buffer)
  File "C:\Users\rossinim\AppData\Roaming\Python\Python37\site-packages\harvesters-_issue_130-py3.7.egg\harvesters\core.py", line 147, in revoke_buffer
    return self._module.revoke_buffer(buffer)
  File "C:\Users\rossinim\AppData\Local\Programs\Python\Python37\lib\site-packages\genicam\gentl.py", line 4090, in revoke_buffer
    ret = self._revoke_buffer(buffer)
  File "C:\Users\rossinim\AppData\Local\Programs\Python\Python37\lib\site-packages\genicam\gentl.py", line 4095, in _revoke_buffer
    return _gentl.DataStream__revoke_buffer(self, py_obj)
_gentl.BusyException: GenTL exception: Operation cannot be performed. Responsible module is busy. (Message from the source: The required operation cannot be executed because the responsible module/entity is busy executing actions that cannot be performed concurrently with the requested operation.) (ID: -1022)
Traceback (most recent call last):
  File "C:\Users\rossinim\AppData\Local\Programs\Python\Python37\lib\weakref.py", line 648, in _exitfunc
    f()
  File "C:\Users\rossinim\AppData\Local\Programs\Python\Python37\lib\weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\rossinim\AppData\Roaming\Python\Python37\site-packages\harvesters-_issue_130-py3.7.egg\harvesters\core.py", line 2366, in _destroy
    self._parent._destroy_image_acquirer(self)
  File "C:\Users\rossinim\AppData\Roaming\Python\Python37\site-packages\harvesters-_issue_130-py3.7.egg\harvesters\core.py", line 2998, in _destroy_image_acquirer
    ia._release_data_streams()
  File "C:\Users\rossinim\AppData\Roaming\Python\Python37\site-packages\harvesters-_issue_130-py3.7.egg\harvesters\core.py", line 2370, in _release_data_streams
    self._release_buffers()
  File "C:\Users\rossinim\AppData\Roaming\Python\Python37\site-packages\harvesters-_issue_130-py3.7.egg\harvesters\core.py", line 2400, in _release_buffers
    _ = data_stream.revoke_buffer(buffer)
  File "C:\Users\rossinim\AppData\Roaming\Python\Python37\site-packages\harvesters-_issue_130-py3.7.egg\harvesters\core.py", line 147, in revoke_buffer
    return self._module.revoke_buffer(buffer)
  File "C:\Users\rossinim\AppData\Local\Programs\Python\Python37\lib\site-packages\genicam\gentl.py", line 4090, in revoke_buffer
    ret = self._revoke_buffer(buffer)
  File "C:\Users\rossinim\AppData\Local\Programs\Python\Python37\lib\site-packages\genicam\gentl.py", line 4095, in _revoke_buffer
    return _gentl.DataStream__revoke_buffer(self, py_obj)
_gentl.BusyException: GenTL exception: Operation cannot be performed. Responsible module is busy. (Message from the source: The required operation cannot be executed because the responsible module/entity is busy executing actions that cannot be performed concurrently with the requested operation.) (ID: -1022)
Traceback (most recent call last):
  File "C:\Users\rossinim\AppData\Local\Programs\Python\Python37\lib\weakref.py", line 648, in _exitfunc
    f()
  File "C:\Users\rossinim\AppData\Local\Programs\Python\Python37\lib\weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\rossinim\AppData\Roaming\Python\Python37\site-packages\harvesters-_issue_130-py3.7.egg\harvesters\core.py", line 2870, in _reset
    ia._destroy()
  File "C:\Users\rossinim\AppData\Roaming\Python\Python37\site-packages\harvesters-_issue_130-py3.7.egg\harvesters\core.py", line 2366, in _destroy
    self._parent._destroy_image_acquirer(self)
  File "C:\Users\rossinim\AppData\Roaming\Python\Python37\site-packages\harvesters-_issue_130-py3.7.egg\harvesters\core.py", line 2998, in _destroy_image_acquirer
    ia._release_data_streams()
  File "C:\Users\rossinim\AppData\Roaming\Python\Python37\site-packages\harvesters-_issue_130-py3.7.egg\harvesters\core.py", line 2370, in _release_data_streams
    self._release_buffers()
  File "C:\Users\rossinim\AppData\Roaming\Python\Python37\site-packages\harvesters-_issue_130-py3.7.egg\harvesters\core.py", line 2400, in _release_buffers
    _ = data_stream.revoke_buffer(buffer)
  File "C:\Users\rossinim\AppData\Roaming\Python\Python37\site-packages\harvesters-_issue_130-py3.7.egg\harvesters\core.py", line 147, in revoke_buffer
    return self._module.revoke_buffer(buffer)
  File "C:\Users\rossinim\AppData\Local\Programs\Python\Python37\lib\site-packages\genicam\gentl.py", line 4090, in revoke_buffer
    ret = self._revoke_buffer(buffer)
  File "C:\Users\rossinim\AppData\Local\Programs\Python\Python37\lib\site-packages\genicam\gentl.py", line 4095, in _revoke_buffer
    return _gentl.DataStream__revoke_buffer(self, py_obj)
_gentl.BusyException: GenTL exception: Operation cannot be performed. Responsible module is busy. (Message from the source: The required operation cannot be executed because the responsible module/entity is busy executing actions that cannot be performed concurrently with the requested operation.) (ID: -1022)
```

Am I doing something wrong?

**To Reproduce**
(See above).

**Expected behavior**
I would expect acquisition to stop gently, without raising errors.

**Screenshots**
(No screenshots provided).

**Desktop (please complete the following information):**
 - OS: Windows 10, 64 bit
 - Python: Intel Distribution for Python 3.7.4 and standard Python 3.7 (I tried both)
 - Harvester: from 1.1.1
 - GenTL Producer: Omron SENTECH (I used the official Omron SENTECH SDK and the provided official .cti file)
 - Camera: STC-MCS241U3V

**Additional context**

**Comment by kazunarikudo** [comment]
@bobcorn Hi, Marco. Thank you for the report. I think I have heard the phenomenon that happens with Sentech GenTL Producer by someone before. I could not get into further at the moment because there's no sufficient information. Okay, I will try to ask a GenICam colleague at Sentech but I am not sure if he's still working for the company but it's worth trying. Probably this issue might take some time because it involves other 3rd party software so I hope you understand the situation. In the meantime, could you use Matrix Vision if you don't mind? There could be a specific reason to use Sentech's one but as far as I know, MV is awesome at its quality and GenICam feature coverage.

**Comment by bobcorn** [comment]
Hi @kazunarikudo. Thank you for explaning to me the reason of this issue. I didn't know that it was caused by Sentech's GenTL Producer.

Of course, if a fix will be possible, I will stay tuned for it. Meanwhile, I will use Matrix Vision if it doesn't raise the error.

Thank you again for you careful help.

**Comment by kazunarikudo** [comment]
@bobcorn Hi, I hope you are doing well. I had a few rounds of discussion with one of my familiar engineers at SENTECH and he eventually gave me a revised version of CTI file. Could you send me an email so that I can tell you the link where you can download that? You should be able to find my email address on my GitHub profile page. Thanks. /Kazunari

**Comment by bobcorn** [comment]
Hi @kazunarikudo, fortunately I'm fine, and I sincerely hope the same for you. Of course, I will send you an email shortly. Thank you so much, really, for taking time to investigate this issue.

**Comment by kazunarikudo** [comment]
The issue has been fixed on the SENTECH side (thank you, Mr. Kawaguchi!). The fix would be bundled in the upcoming release, SentechSDKv1.1.2. People who are interested in their SDK, you should keep an eye on that. /Kazunari

**Comment by jas1989** [comment]
Hi, I've encountered the same issue of @bobcorn. Could you also share the 1.1.2 .cti file version with me? (I've only find the 1.0.6 version online). Thanks

**Comment by kazunarikudo** [comment]
@jas1989 Hi, I believe that version is not a secret so I highly recommend you to ask a contact person at SENTECH or their distributor. Regards, Kazunari.
