### ISSUE TITLE
HickVision Camera GenTL exception: The requested resource is exhausted.

### ISSUE THREAD

**Issue by PedrofRodenasRVT** [genicam/harvesters#143]
My camera is 
**manufactured by : HikVision**
**model: MV-CA050-10GM**
**SO: Windows10**
**Python Version: 3.7**
**Harvesters Version: 1.1.1**

When I execute the code:

```
h = Harvester()
h.add_cti_file('C:\\Program Files (x86)\\Common Files\\MVS\\Runtime\\Win64_x64\\MvProducerGEV.cti')
h.update_device_info_list()
print(h.device_info_list)
```

I get :

[(id_='Hikvision MV-CA050-10GC (02D38823085)', vendor='Hikvision', model='MV-CA050-10GC', tl_type='GEV', user_defined_name=None, serial_number='02D38823085', version='V2.9.0 180125')]

But when I try to create an ImageAdquisition object:

```
ia = h.create_image_acquirer(list_index=0)
```

I get the following error:

Traceback (most recent call last):
  File "D:\Pedro\Anaconda\envs\harvester\lib\site-packages\harvesters\core.py", line 1486, in __init__
    xml_dir=self._xml_dir
  File "D:\Pedro\Anaconda\envs\harvester\lib\site-packages\harvesters\core.py", line 2493, in _get_port_connected_node_map
    port=port, file_path=file_path, logger=logger, xml_dir=xml_dir
  File "D:\Pedro\Anaconda\envs\harvester\lib\site-packages\harvesters\core.py", line 2389, in _retrieve_file_path
    if len(port.url_info_list) > 0:
  File "D:\Pedro\Anaconda\envs\harvester\lib\site-packages\genicam\gentl.py", line 5183, in _get_url_info_list
    return _gentl.Port__get_url_info_list(self)
_gentl.ResourceExhaustedException
2020-04-02 18:23:29,377 :: harvesters.core :: ERROR :: GenTL exception: The requested resource is exhausted. (Message from the source: ) (ID: -1020)
Traceback (most recent call last):
  File "D:\Pedro\Anaconda\envs\harvester\lib\site-packages\harvesters\core.py", line 1497, in __init__
    xml_dir=self._xml_dir
  File "D:\Pedro\Anaconda\envs\harvester\lib\site-packages\harvesters\core.py", line 2493, in _get_port_connected_node_map
    port=port, file_path=file_path, logger=logger, xml_dir=xml_dir
  File "D:\Pedro\Anaconda\envs\harvester\lib\site-packages\harvesters\core.py", line 2389, in _retrieve_file_path
    if len(port.url_info_list) > 0:
  File "D:\Pedro\Anaconda\envs\harvester\lib\site-packages\genicam\gentl.py", line 5183, in _get_url_info_list
    return _gentl.Port__get_url_info_list(self)
_gentl.ResourceExhaustedException: GenTL exception: The requested resource is exhausted. (Message from the source: ) (ID: -1020)
Traceback (most recent call last):

  File "<ipython-input-2-5eeaad1b2118>", line 1, in <module>
    ia = h.create_image_acquirer(list_index=0)

  File "D:\Pedro\Anaconda\envs\harvester\lib\site-packages\harvesters\core.py", line 2723, in create_image_acquirer
    file_path=file_path

  File "D:\Pedro\Anaconda\envs\harvester\lib\site-packages\harvesters\core.py", line 1516, in __init__
    module=device, node_map=node_map, parent=self._interface

AttributeError: 'ImageAcquirer' object has no attribute '_interface'

**Comment by kazunarikudo** [comment]
@PedrofRodenasRVT Hi, Pedro. Thank you for trying out Harvester and for the report. You told me you confirmed the phenomenon with version 1.1.1 so could you try version 1.2 then? Let me know if it does not resolve the issue. /Kazunari

**Comment by PedrofRodenasRVT** [comment]
> @PedrofRodenasRVT Hi, Pedro. Thank you for trying out Harvester and for the report. You told me you confirmed the phenomenon with version 1.1.1 so could you try version 1.2 then? Let me know if it does not resolve the issue. /Kazunari

Yes, I've also tried with the last recent release 1.2 and throws the same error

**Comment by kazunarikudo** [comment]
@PedrofRodenasRVT Thank you for making a try with the latest version. I'm sorry but I feel consulting with them should be much productive as far as I hear the phenomenon even if it requires Harvester to fix some points of it; the current situation is like this: the Producer complains something but I do not understand "WHY" they do so. HikVision has told me that they are interested in Harvester as well. Could you privately send your email address so that they can reach out to you? /Kazunari

**Comment by kazunarikudo** [comment]
@PedrofRodenasRVT I'm going to close this ticket but please feel free to reopen anytime when needed. /Kazunari
