### ISSUE TITLE
Problem with Basler after harvester upgrade

### ISSUE THREAD

**Issue by queisser** [genicam/harvesters#191]
I recently upgraded harvesters from 0.2.5 to 1.2.7. I'm working with Basler cameras, with the latest Pylon SDK (6.12) and my code worked okay before the upgrade. I'm getting an error from create_image_acquirer, here's an interactive session that shows the problem with stack trace at the end

**
>>> from harvesters.core import Harvester
>>> h=Harvester()
>>> h.add_file(r"C:\Program Files\Basler\pylon 6\Runtime\x64\ProducerU3V.cti")
>>> h.update()
>>> ia=h.create_image_acquirer(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\source\Nanostrobe\NanoPy\venv-new-harvester\lib\site-packages\harvesters\core.py", line 3247, in create_image_acquirer
    file_path=file_path
  File "C:\source\Nanostrobe\NanoPy\venv-new-harvester\lib\site-packages\harvesters\core.py", line 1746, in __init__
    xml_dir_to_store=self._xml_dir, file_path=file_path_
  File "C:\source\Nanostrobe\NanoPy\venv-new-harvester\lib\site-packages\harvesters\core.py", line 2964, in _get_port_connected_node_map
    port=port, file_path_to_load=file_path, logger=logger, xml_dir_to_store=xml_dir_to_store
  File "C:\source\Nanostrobe\NanoPy\venv-new-harvester\lib\site-packages\harvesters\core.py", line 2882, in _retrieve_file_path
    binary_data=binary_data
  File "C:\source\Nanostrobe\NanoPy\venv-new-harvester\lib\site-packages\harvesters\core.py", line 2941, in _save_file
    with io.open(file_path, mode, encoding="utf-8") as f:
**ValueError: binary mode doesn't take an encoding argument**
>>>** 
 - OS: Windows 10 x64
 - Python: 3.6.6
 - Harvester: 1.2.7
 - GenTL Producer: Basler (cti file is ProducerU3V.cti) for USB3 cameras
 - Camera:  acA1920

I an switch my virtual Python environment back to the old version and everything works. I'd like to take advantage of the callbacks, though, so I'd like to upgrade my harvesters.

Thanks,
Andrew Queisser
hp Corvallis

**Comment by kazunarikudo** [comment]
@queisser Hi, thank you for the report. Could you try out the head version of the master branch, please? /Kazunari

**Comment by queisser** [comment]
Yes, it works with the latest from master. Thanks for the speedy reply!

Andrew

**Comment by kazunarikudo** [comment]
@queisser Hi, Andrew. Thank you for the update. I'm going to close this ticket but please feel free to create/open another ticket if you should have any requests regarding the callback feature. /Kazunari
