### ISSUE TITLE
Fail to install library on python 3.7

### ISSUE THREAD

**Issue by Drosaca** [genicam/harvesters#228]
**Describe the bug**
I can't execute the first import 
from harvesters.core import Harvester
```
>>> import harvesters.core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/vEnv/lib/python3.7/site-packages/harvesters/core.py", line 37, in <module>
    from genicam.genapi import NodeMap
ModuleNotFoundError: No module named 'genicam'
```
```
pip3 install harvesters
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: harvesters in /home/pi/vEnv/lib/python3.7/site-packages (1.0.0)
Requirement already satisfied: numpy in /home/pi/vEnv/lib/python3.7/site-packages (from harvesters) (1.19.2)
Requirement already satisfied: genicam2<1 in /home/pi/vEnv/lib/python3.7/site-packages (from harvesters) (0.0.0.3)
```

the only package I have after install is genicam2 so i tried to create a symlink and get this error

```
Traceback (most recent call last):
  File "/home/pi/vEnv/lib/python3.7/site-packages/genicam/genapi.py", line 19, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
...
 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/pi/vEnv/lib/python3.7/site-packages/genicam/_genapi.so: invalid ELF header
```

i'm on a Raspberry4 with python3.7
uname -a: Linux raspberrypi 5.4.72-v7l+ SMP BST 2020 armv7l GNU/Linux

**Comment by kazunarikudo** [comment]
@Drosaca Hi, I am afraid but the `genicam` package is not available for ARMs. Regards, Kazunari.
