### ISSUE TITLE
JAI GigE camera returns multiple devices with identical properties 

### ISSUE THREAD

**Issue by TecKonstantin** [genicam/harvesters#231]
**Describe the Bug**
When using a JAI GigE BM-500GE Camera I get two identical devices with identical entry.
And because they are the same I can't differentiate them and get a subsequent error.

Probably me doing something wrong 

**To Reproduce**
Using the demo program in the examples and the JAI Camera

**Expected Behavior**
Only one device in List or at least not the exact same 

**Screenshots**
```python
from harvesters.core import Harvester
import numpy as np

h = Harvester()
print(h.add_file('C:/Program Files/JAI/SDK/bin/JaiGevTL.cti'))
print("file",h.files)
h.update()
print(len(h.device_info_list))

print(h.device_info_list[0])
print(h.device_info_list[1])

ia = h.create_image_acquirer(serial_number='U501496', vendor='JAI Ltd., Japan')
print ("ia",ia)


ia.remote_device.node_map.Width.value = 1000
ia.remote_device.node_map.Height.value = 1000
ia.remote_device.node_map.PixelFormat.value = 'Mono8'
ia.start_acquisition()

with ia.fetch_buffer() as buffer:
    component = buffer.payload.components[0]
    _1d = component.data
    print('1D: {0}'.format(_1d))
    _2d = component.data.reshape(component.height, component.width)
    print('2D: {0}'.format(_2d))
    print('AVE: {0}, MIN: {1}, MAX: {2}'.format(np.average(_2d), _2d.min(), _2d.max()))


ia.stop_acquisition()
ia.destroy()
h.reset()
```
Output 
```None
file ['C:/Program Files/JAI/SDK/bin/JaiGevTL.cti']
GenTL producer does not implement IFGetParentTL
GenTL producer does not implement DevGetParentIF
GenTL producer does not implement DSGetParentDev
GenTL producer does not implement DSGetNumBufferParts
GenTL producer does not implement DSGetBufferPartInfo
2
(id_='MAC->00-0C-DF-04-04-EB::JAI Ltd., Japan::BM-500GE', vendor='JAI Ltd., Japan', model='BM-500GE', tl_type='GEV', user_defined_name=None, serial_number='U501496', version=None)
(id_='MAC->00-0C-DF-04-04-EB::JAI Ltd., Japan::BM-500GE', vendor='JAI Ltd., Japan', model='BM-500GE', tl_type='GEV', user_defined_name=None, serial_number='U501496', version=None)
Traceback (most recent call last):
  File "C:/Users/Konstantin/PycharmProjects/CTscanner/CameraCapture.py", line 13, in <module>
    ia = h.create_image_acquirer(serial_number='U501496', vendor='JAI Ltd., Japan')
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 3223, in create_image_acquirer
    raise ValueError(
ValueError: You have two or more candidates. You have to pass one or more keys so that a single candidate is specified.

Process finished with exit code 1
```

**Configuration**

 - OS: Win7 64
 - Python: 3.8.8
 - Harvester: 1.2.8
 - GenTL Producer: JAI
 - Camera: BM-500GE

**Comment by TecKonstantin** [comment]
```python
h.create_image_acquirer(1)
```
Seams to work for selection now I have to further debug if it works, but still don't know why there are two and only the second one seams to work.

**Comment by kazunarikudo** [comment]
@TecKonstantin Hi, the list consists of entities observed through the driver software. Especially, GigE Vision GenTL Producers cover both a socket driver and a filter driver so I guess you are seeing the same device twice. I recommend you to check which drivers are activated and enable either one if needed. Best regards, Kazunari.

**Comment by TecKonstantin** [comment]
Thanks that's sound reasonable, I will check.
I get related errors with both of them.
I will test it on a clean system etc. if it is ok I might get back to you if I find something new. Thanks!

```python
Traceback (most recent call last):
  File "C:/Users/Konstantin/PycharmProjects/CTscanner/CameraCapture.py", line 27, in <module>
    buffer = ia.fetch_buffer()
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 2722, in fetch_buffer
    _buffer = Buffer(
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 1126, in __init__
    self._payload = self._build_payload(
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 1261, in _build_payload
    payload = PayloadImage(
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 1437, in __init__
    self._build_component(
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 1359, in _build_component
    return Component2DImage(
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 837, in __init__
    self._data = self._to_np_array(proxy)
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 880, in _to_np_array
    self._buffer.raw_buffer, count=int(nr_bytes),
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\genicam\gentl.py", line 4572, in _get_raw_buffer
    return _gentl.Buffer__get_raw_buffer(self)
SystemError: \Objects\listobject.c:248: bad argument to internal function
```
and

```python
Traceback (most recent call last):
  File "C:/Users/Konstantin/PycharmProjects/CTscanner/CameraCapture.py", line 27, in <module>
    buffer = ia.fetch_buffer()
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 2722, in fetch_buffer
    _buffer = Buffer(
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 1126, in __init__
    self._payload = self._build_payload(
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 1261, in _build_payload
    payload = PayloadImage(
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 1437, in __init__
    self._build_component(
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 1359, in _build_component
    return Component2DImage(
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 837, in __init__
    self._data = self._to_np_array(proxy)
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 880, in _to_np_array
    self._buffer.raw_buffer, count=int(nr_bytes),
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\genicam\gentl.py", line 4572, in _get_raw_buffer
    return _gentl.Buffer__get_raw_buffer(self)
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\weakref.py", line 642, in _exitfunc
    f()
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 1923, in destroy
    self.stop_acquisition()
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 2887, in stop_acquisition
    self._release_buffers()
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 2947, in _release_buffers
    _ = data_stream.revoke_buffer(buffer)
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 246, in revoke_buffer
    return self._module.revoke_buffer(buffer)
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\genicam\gentl.py", line 4090, in revoke_buffer
    ret = self._revoke_buffer(buffer)
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\genicam\gentl.py", line 4095, in _revoke_buffer
    return _gentl.DataStream__revoke_buffer(self, py_obj)
_gentl.ErrorException: GenTL exception: Unspecified runtime exception. (Message from the source: Unknown Error) (ID: -1001)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\weakref.py", line 642, in _exitfunc
    f()
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 3402, in _reset
    ia.destroy()
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 1925, in destroy
    self._release_data_streams()
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 2916, in _release_data_streams
    self._release_buffers()
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 2947, in _release_buffers
    _ = data_stream.revoke_buffer(buffer)
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\harvesters\core.py", line 246, in revoke_buffer
    return self._module.revoke_buffer(buffer)
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\genicam\gentl.py", line 4090, in revoke_buffer
    ret = self._revoke_buffer(buffer)
  File "C:\ProgramData\Anaconda3\envs\CTScanner\lib\site-packages\genicam\gentl.py", line 4095, in _revoke_buffer
    return _gentl.DataStream__revoke_buffer(self, py_obj)
_gentl.ErrorException: GenTL exception: Unspecified runtime exception. (Message from the source: Unknown Error) (ID: -1001)
```

**Comment by TecKonstantin** [comment]
Ok sorry, yes it was the filterer driver, I did not execute with the administrator to disable it. But unfortunately it stops at 
```python 
buffer = ia.fetch_buffer()
``` 
and does not proceed, the same thing happens with your GUI program example.
