### ISSUE TITLE
"Failed processing buffer payload" on start_acquisition()

### ISSUE THREAD

**Issue by rfiff** [genicam/harvesters#253]
**Describe the Bug**
I got 4 cameras on 2 framegrabbers. Each of the cameras occupies 2 coaxpress lanes on the framegrabber. I can detect all of the cameras via harvester, and also read and write to the framegrabbers and cameras (e.g. exposure time) via the node map. For testing purposes I unplugged 3 of the 4 cameras. As soon as I try acquiring images (ia.start_acquisition()), I get the following error message:

```
GenTL producer does not implement IFGetParentTL
GenTL producer does not implement DevGetParentIF
GenTL producer does not implement DSGetParentDev
GenTL producer does not implement DSGetNumBufferParts
GenTL producer does not implement DSGetBufferPartInfo
[(id_='Channel #1', vendor='Unknown Vendor', model='Unknown Model', tl_type='CXP', user_defined_name=None, serial_number='SN1234', version=None), (id_='Channel #3', vendor='Unknown Vendor', model='Unknown Model', tl_type='CXP', user_defined_name=None, serial_number='SN1234', version=None), (id_='Channel #1', vendor='Unknown Vendor', model='Unknown Model', tl_type='CXP', user_defined_name=None, serial_number='SN1234', version=None), (id_='Channel #3 (000000000000122)', vendor='Mikrotron GmbH', model='MC1289', tl_type='CXP', user_defined_name=None, serial_number='SN1234', version=None)]



Traceback (most recent call last):
  File "c:/Users/friff/02-Harvesters/harvester_test.py", line 94, in <module>
    ia.start_acquisition()
  File "C:\Users\friff\02-Harvesters\env\lib\site-packages\harvesters\core.py", line 2507, in start_acquisition
    data_stream=ds, buffers=self._announced_buffers
  File "C:\Users\friff\02-Harvesters\env\lib\site-packages\harvesters\core.py", line 2916, in _queue_announced_buffers
    data_stream.queue_buffer(buffer)
  File "C:\Users\friff\02-Harvesters\env\lib\site-packages\harvesters\core.py", line 212, in queue_buffer
    self._module.queue_buffer(announced_buffer)
  File "C:\Users\friff\02-Harvesters\env\lib\site-packages\genicam\gentl.py", line 3813, in queue_buffer
    return _gentl.DataStream_queue_buffer(self, buffer, clear_buffer)
_gentl.ErrorException: GenTL exception: Unspecified runtime exception. (Message from the source: Failed processing buffer payload (PHX_BUFFER_MAKE_READY) Failed to Read CXP Device Addr=0x00000004, NumBytesToRead=0x00000004, BytesRead=0x00000000, with Library Error 0x0000000f (MDA_CxpIoctl returned error code 0xf) [DSGetBufferInfo]) (ID: -1001)
```

To narrow down possible subjects causing the issue above, I shortened the code to the bare minimum. The code raising the exception above is as follows:
```
from harvesters.core import Harvester
import os

h = Harvester()
path = os.getenv("GENICAM_GENTL64_PATH") + "TLActiveSilicon.cti"

h.add_file(path)
h.update()

print(h.device_info_list)
print("\n\n")

ia = h.create_image_acquirer(3)

ia.start_acquisition()

exit()
```

However, using ActiveCapture I can view a live stream. As far as I understand, this software uses the GenTL interface as well. Further, using another firmware on the framegrabber (but also only 2 lanes for one camera), which supports only one camera per framegrabber, I can obtain images. Unfortunately I would need the complete setup with all four cameras on two framegrabbers working.

**Configuration**

I am using the following setup:
- Framegrabber: 2x FireBird CoaXPress Frame Grabber (Quad CXP-6)  (AS-FBD-4XCXP6-2PE8)
- Camera: 4x Mikrotron  EoSens 12CXP+  (MC1289) 
- OS: Windows 10
- Python 3.7.9
- Harvester: 1.3.2
- GenTL Producer: ActiveSilicon (TLActiveSilicon.cti)

**Actions You Have Taken**
 
- [x] I've read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).

Also had a look into all documentation (cameras, framegrabbers, phx references, harvester documentation, core.py..) I could find. Unfortunately I was not able to find any further information on "MDA_CxpIoctl" which seems to be the C++ (?) function causing the issue. 

Any help would be greatly appreciated!

**Comment by rfiff** [comment]
I was able to resolve the issue, the cti file was faulty. Active Silicon was able to provide me with an updated one.
