### ISSUE TITLE
how to set frequency

### ISSUE THREAD

**Issue by sawk1** [genicam/harvesters#259]
i connected the camera and can see the photo from it, but in the documentation i didnt find any method how i can set frequency on it, i believe that it something like:

`ia.remote_device.node_map.Frequency.value = 15100`

but as i said, there is nothing in the documentation.

**Comment by kazunarikudo** [comment]
Hi, perhaps you're trying to work with `AcquisitionFrameRate`; I believe you know the answer. Please take a look at [this section](https://github.com/genicam/harvesters#id55) with [SFNC](https://www.emva.org/wp-content/uploads/GenICam_SFNC_v2_6.pdf). Regards, Kazunari.

**Comment by sawk1** [comment]
Thank you, it is what im looking for!
im using this code to make my camera work with the parameters:
```
from harvesters.core import Harvester
import cv2

h = Harvester()
h.add_file('/opt/mvIMPACT_Acquire/lib/x86_64/mvGenTLProducer.cti')
h.update()
ia = h.create_image_acquirer(0)
ia.remote_device.node_map.Width.value = 4096
ia.remote_device.node_map.Height.value = 4096
ia.remote_device.node_map.PixelFormat.value = 'mono10'
ia.remote_device.node_map.AcquisitionFrameRate.value = 15100
ia.start_acquisition()
buffer = ia.fetch_buffer()
payload = buffer.payload
component = payload.components[0]
width = component.width
height = component.height
data_format = component.data_format
content = component.data.reshape(height, width)
cv2.imwrite('content.jpg', content)
```
but it showing this error:

`Traceback (most recent call last):
  File "/home/fm/miniconda3/lib/python3.7/site-packages/genicam/genapi.py", line 2080, in __getattr__
    return self.get_node(attribute)
  File "/home/fm/miniconda3/lib/python3.7/site-packages/genicam/genapi.py", line 2032, in get_node
    return _genapi.NodeMap_get_node(self, key)
_genapi.LogicalErrorException: Node not existing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ned.py", line 16, in <module>
    ia.remote_device.node_map.AcquisitionFrameRate.value = 1000
  File "/home/fm/miniconda3/lib/python3.7/site-packages/genicam/genapi.py", line 2084, in __getattr__
    raise AttributeError from e
AttributeError
`

**Comment by sawk1** [comment]
i did
`print(dir(ia.remote_device.node_map))`
and it show me this:
`'AcquisitionControl', 'AcquisitionLineRate', 'AcquisitionLineRateEnable', 'AcquisitionMode', 'AcquisitionStart', 'AcquisitionStop', 'AnalogControl', 'BlackLevel', 'BlackLevelSelector', 'DeviceCharacterSet', 'DeviceControl', 'DeviceLinkHeartbeatTimeout', 'DeviceLinkSelector', 'DeviceManifestEntrySelector', 'DeviceManifestPrimaryURL', 'DeviceManufacturerInfo', 'DeviceModelName', 'DeviceRegistersEndianness', 'DeviceSFNCVersionMajor', 'DeviceSFNCVersionMinor', 'DeviceSFNCVersionSubMinor', 'DeviceScanType', 'DeviceSerialNumber', 'DeviceStartupMode', 'DeviceTLType', 'DeviceTLVersionMajor', 'DeviceTLVersionMinor', 'DeviceTemperature', 'DeviceTemperatureSelector', 'DeviceUserID', 'DeviceVendorName', 'DeviceVersion', 'DigitalIOControl', 'EncoderControl', 'EncoderDivider', 'EncoderMode', 'EncoderOutputMode', 'EncoderReset', 'EncoderResetActivation', 'EncoderResetSource', 'EncoderSelector', 'EncoderSourceA', 'EncoderSourceB', 'EncoderStatus', 'EncoderTimeout', 'EncoderValue', 'EncoderValueAtReset', 'ExposureMode', 'ExposureTime', 'FBInit', 'Gain', 'GainSelector', 'Gamma', 'GevCCP', 'GevCurrentDefaultGateway', 'GevCurrentIPAddress', 'GevCurrentIPConfigurationDHCP', 'GevCurrentIPConfigurationLLA', 'GevCurrentIPConfigurationPersistentIP', 'GevCurrentSubnetMask', 'GevFirstURL', 'GevInterfaceSelector', 'GevMACAddress', 'GevMCDA', 'GevMCPHostPort', 'GevMCRC', 'GevMCSP', 'GevMCTT', 'GevPersistentDefaultGateway', 'GevPersistentIPAddress', 'GevPersistentSubnetMask', 'GevSCDA', 'GevSCPD', 'GevSCPHostPort', 'GevSCPInterfaceIndex', 'GevSCPSDoNotFragment', 'GevSCPSFireTestPacket', 'GevSCPSPacketSize', 'GevSecondURL', 'GevStreamChannelSelector', 'GevSupportedOption', 'GevSupportedOptionSelector', 'GevTimestampTickFrequency', 'GigEVision', 'Height', 'HeightMax', 'ImageFormatControl', 'LineFormat', 'LineInverter', 'LineMode', 'LineSelector', 'LineSource', 'LineStatus', 'NED_AdditionalFeatures', 'NED_AnalogGain', 'NED_DeviceFirmwareBootID', 'NED_DummyFrameOutputTimeout', 'NED_FFCMode', 'NED_FPNCalibration', 'NED_FactoryOnly', 'NED_InternalResultCode', 'NED_InternalResultString', 'NED_LineMaskTimeF', 'NED_LineMaskTimeR', 'NED_PRNUCalibration', 'NED_PRNUTarget', 'OffsetX', 'OffsetY', 'PayloadSize', 'PixelFormat', 'ReverseX', 'Root', 'SensorHeight', 'SensorWidth', 'TestPattern', 'TimestampLatch', 'TimestampLatchValue', 'TimestampReset', 'TransportLayerControl', 'TriggerActivation', 'TriggerMode', 'TriggerSelector', 'TriggerSource', 'UserSetControl', 'UserSetDefault', 'UserSetLoad', 'UserSetSave', 'UserSetSelector', 'Width', 'WidthMax', '__class__', '__del__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__swig_destroy__', '__swig_getmethods__', '__swig_setmethods__', '__weakref__', '_concrete_port', '_connect', '_destroy', '_get_device_info', '_get_device_name', '_get_node', '_get_nodes', '_invalidate_nodes', 'clear_xml_cache', 'connect', 'device_info', 'disconnect', 'get_node', 'has_node', 'load_xml_from_file', 'load_xml_from_string', 'load_xml_from_zip_file', 'nodes', 'pointer', 'poll', 'rr_rw_64_Value', 'rr_rw_64_ValueDecimal', 'rr_rw_Index', 'rr_rw_Value', 'rr_rw_ValueDecimal', 'this'`

after looking at the parameters, i changed AcquisitionFrameRate to AcquisitionLineRate
so far, it seems like it, thank you for your beautiful job
