### ISSUE TITLE
KeyError: 258

### ISSUE THREAD

**Issue by junneng-my** [genicam/harvesters#316]
**Describe the Bug**

Traceback (most recent call last):
  File "test_case.py", line 886, in <module>
    run_cam.check_gain_mean_img()
  File "test_case.py", line 822, in check_gain_mean_img
    with self.ia.fetch_buffer() as buffer:
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 2816, in fetch_buffer
    logger=self._logger
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 1135, in __init__
    logger=self._logger
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 1268, in _build_payload
    buffer=buffer, node_map=node_map, logger=logger
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 1447, in __init__
    buffer=buffer, node_map=node_map
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 1363, in _build_component
    symbolic = dict_by_ints[data_format]
KeyError: 258

The above message show when I run my code to start the acquisition on PC B. My code can run on another PC A with cxp1.0 frame grabber. But when I run on this PC then it will show this error. The harvesters version is 1.3.2 and python is 3.7.6 in both PC. If I use euresys genicam browser I am able to start the streaming from both PC.  If I change harvesters to 1.3.4 it will show another error message.

 self.ia.start_acquisition()
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\genicam\genapi.py", line 2080, in __getattr__
    return self.get_node(attribute)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\genicam\genapi.py", line 2032, in get_node
    return _genapi.NodeMap_get_node(self, key)
_genapi.LogicalErrorException: Node not existing

**To Reproduce**
1. run below code will see the error
2. 
from harvesters.core import Harvester
from PIL import Image
from time import sleep
h = Harvester()
h.add_file('C:\\Program Files\\Euresys\\eGrabber\\cti\\x86_64\\coaxlink.cti')
h.update()
ia = h.create_image_acquirer(0)
ia.start_acquisition()
count =0 
firstmean = 0
fail_dict ={}
diff_mean = 0
img_list = []

for i in range(1,17,1):
    gain =i*1000
    
    
    with ia.fetch_buffer() as buffer:
        
        component = buffer.payload.components[0]
    
       
        _2d = component.data.reshape(
            component.height, component.width
        )
        img_list.append(_2d)
        
        print(f'img with gain{i}')
        img = Image.fromarray(_2d)
        
        #img.show()
    ia.stop_acquisition()
    sleep(0.1)

3. Traceback (most recent call last):
  File "test_hr.py", line 26, in <module>
    with ia.fetch_buffer() as buffer:
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 2816, in fetch_buffer
    logger=self._logger
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 1135, in __init__
    logger=self._logger
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 1268, in _build_payload
    buffer=buffer, node_map=node_map, logger=logger
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 1447, in __init__
    buffer=buffer, node_map=node_map
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 1363, in _build_component
    symbolic = dict_by_ints[data_format]
KeyError: 258

**Expected Behavior**
To able capture image

**Screenshots**

**Configuration**

PC A (working fine)
 - OS: [windows 10]
 - Python: [3.7.6]
 - Harvester: [1.3.2]
 - GenTL Producer: [Euresys GenICam Browser, 15.0.3.586]
 - Camera: [self]
 - cxp 1.0

PC B (bug occur)
- OS: [windows 11]
 - Python: [3.7.6]
 - Harvester: [1.3.2]
 - GenTL Producer: [Euresys GenICam Browser, 21.0.0.16]
 - Camera: [self]
 - cxp 2.0
**Reproducibility**

This phenomenon can be reproduced by other versions:

-  Yes, but will show another error message

If so, please list up the reproducible versions you have confirmed:

PC B (bug occur)
- OS: [windows 11]
 - Python: [3.7.6]
 - Harvester: [1.3.4]
 - GenTL Producer: [Euresys GenICam Browser, 21.0.0.16]
 - Camera: [self]
 -  cxp 2.0
new error message

Traceback (most recent call last):
  File "test_hr.py", line 26, in <module>
    with ia.fetch_buffer() as buffer:
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 2823, in fetch_buffer
    logger=self._logger
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 1135, in __init__
    logger=self._logger
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 1268, in _build_payload
    buffer=buffer, node_map=node_map, logger=logger
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 1454, in __init__
    buffer=buffer, node_map=node_map
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 1374, in _build_component
    logger=self._logger
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 838, in __init__
    proxy = Dictionary.get_proxy(symbolic=self.data_format)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 999, in data_format
    return dict_by_ints[self.data_format_value]
KeyError: 258

**Actions You Have Taken**
for harvester 1.3.2 if I change the below code in (site-packages\harvesters\core.py)
![image](https://user-images.githubusercontent.com/52816448/159423154-4a115a40-1795-4d8d-90c5-82ce711a7403.png)
to
![image](https://user-images.githubusercontent.com/52816448/159423403-53baabb3-7420-4f0e-8636-57812de1a36d.png)
then the error will change to 

Traceback (most recent call last):
  File "test_hr.py", line 26, in <module>
    with ia.fetch_buffer() as buffer:
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 2823, in fetch_buffer
    logger=self._logger
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 1135, in __init__
    logger=self._logger
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 1268, in _build_payload
    buffer=buffer, node_map=node_map, logger=logger
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 1454, in __init__
    buffer=buffer, node_map=node_map
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 1374, in _build_component
    logger=self._logger
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 838, in __init__
    proxy = Dictionary.get_proxy(symbolic=self.data_format)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\harvesters\core.py", line 999, in data_format
    return dict_by_ints[self.data_format_value]
KeyError: 258

I suspect don't know why the harvester did not catch the GenericException. Hence, it did not get the pixel format from the node map. If it get the pixel format value from the node map then should be no problem. The second error actually is the same as the first error, it just happens in different part of the code.

 
- I've read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).

**Additional context**
I am not sure is it because the gentl producer version is different or because both PC have different cxp frame grabber.

**Comment by kazunarikudo** [comment]
@junneng-my Hi, thank you for the report. I will look into this issue further later and let you know once the issue is resolved. Thanks, Kazunari.

**Comment by junneng-my** [comment]
@kazunarikudo Hi, the pixel format is Mono10. However according to my camera XML file, Mono10 is 0x0102, but in the _pfnc.py Mono10 refer to 0x01100003. When I use Euresys 15.0.3.586, the buffer.pixel_format is working to give the 0x01100003, but when I use Euresys 21.0.0.16, the GenericException will occur and then get the value from node_map.PixelFormat.value. 

According to your message then I think the number 258 is because the XML file state Mono10 is 0x0102. Btw, is it genicam compliance camera must follow Mono10 equal to 0x01100003. Sorry if this is a simple question. Because the camera firmware is write by my company and the XML file also write by ourselves. 

Also today I try with Euresys 16 version. The harvesters is working fine on the PC B above.
Yes, I will try to report to Euresys.
 `try:
            if part:
                
                data_format = part.data_format
            else:
                
                
                data_format = buffer.pixel_format
        except GenericException:
            # As a workaround, we are going to retrive a data format
            # value from the remote device node map; note that there
            # could be a case where the value is not synchronized with
            # the delivered buffer; in addition, note that it:
            
            if node_map:
                
                name = node_map.PixelFormat.value
                if name in dict_by_names:
                    data_format = dict_by_names[name]
                else:
                    raise
            else:
                raise
        
        symbolic = dict_by_ints[data_format]`

**Comment by kazunarikudo** [comment]
Closing: Please feel free to re-open when needed. Thanks.
