### ISSUE TITLE
FLIR thermal gige camera is not recognized.

### ISSUE THREAD

**Issue by iPsych** [genicam/harvesters#335]
**Describe the Bug**
FLIR thermal gige camera is not recognized.
It connects properly with the Thermal Studio in MacOS Catalina, and can be connected and recorded flawlessly in ebusplayer.
So, the GiGe connection itself seems not a problem, but the harvester cannot detect the camera.

**To Reproduce**
1. Connect the Gige thermal camera of FLIR (A35/A65)
2. run harvester gui (https://github.com/genicam/harvesters_gui)
3. No camera detected.
4. eBusPlayer detect and stream the camera output perfectly.

**Sample Code**
 I can show a piece of code that demonstrates the reported phenomenon:

- [ ] Yes
- [x] No
- [ ] (Please select either yes or no.)

 
**Expected Behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem; Note that it is not necessary to put everything as a screenshot! If the source is a text just paste the text because that is much helpful for us.

**Configuration**

 - OS: macOS 10.14 & 10.15 (both tested)
 - Python: 3.7
 - Harvester: 1.3.6
 - GenTL Producer: Not Specified
 - Camera: FLIR A35 thermal / A65 thermal
 - 
**Reproducibility**

This phenomenon can be stably reproduced:

- [x] Yes
- [ ] No.

If applicable, please provide your observation about the reproducibility.

**Actions You Have Taken**
- [x] I've read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).

**Additional context**

**Comment by kazunarikudo** [comment]
Hi, thank you for trying out Harvester. Here's a quick question: Could you tell the GenTL Producer(s) that you have tried? Regards, Kazunari.

**Comment by iPsych** [comment]
@kazunarikudo According to FLIR their protocol is based on GenlCam GenTL 1.5 standard. 
Should I set some option for above?

**Comment by iPsych** [comment]
@kazunarikudo 
Using FLIR provided FLIR_GenTL.cti, The camera can be detected.
However

```
from harvesters.core import Harvester
h = Harvester()
h.add_file('FLIR_GenTL.cti')
h.update()
ia = h.create_image_acquirer(0)
DEVICE_ACCESS_FLAGS_LIST.DEVICE_ACCESS_READONLY
<genicam.gentl.Device; proxy of <Swig Object of type 'std::shared_ptr< GenTLCpp::Device > *' at 0x10301a990> >
(id_='00111C01E08E_A9FE650E_FFFF0000_A9FE6501', vendor='FLIR Systems AB', model='FLIR AX5', tl_type='GEV', user_defined_name=None, serial_number='62600XXX', version='Version 1.0  (02.05.15)')
```

And also can get attribute values
```
 ia.remote_device.node_map.PixelFormat.value
'Mono8'

ia.remote_device.node_map.Width.value
640

ia.remote_device.node_map.Height.value
480
```

However, when I try to set up the pixel format value (and even image Width,Height, get error.
For example,
```
ia.remote_device.node_map.PixelFormat.value = 'Mono14'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/genicam/genapi.py", line 2484, in <lambda>
    __setattr__ = lambda self, name, value: _swig_setattr(self, IEnumeration, name, value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/genicam/genapi.py", line 101, in _swig_setattr
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/genicam/genapi.py", line 93, in _swig_setattr_nondynamic
    object.__setattr__(self, name, value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/genicam/genapi.py", line 2531, in _set_value
    self._primal_set_value(value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/genicam/genapi.py", line 2522, in _primal_set_value
    return _genapi.IEnumeration__primal_set_value(self, entry, verify)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/harvesters/_private/core/port.py", line 54, in write
    self.port.write(address, value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/genicam/gentl.py", line 5016, in write
    return _gentl.Port_write(self, address, buffer)
_gentl.IoException: GenTL exception: Communication error, read or write to remote device failed. (Message from the source: Error writing to remote port register) (ID: -1010)

```

Same for starting acquisition.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/harvesters/core.py", line 1915, in start
    ACQ_START_FLAGS_LIST.ACQ_START_FLAGS_DEFAULT, -1)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/harvesters/core.py", line 138, in m
    return getattr(self._source_object, attribute)(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/genicam/gentl.py", line 3838, in start_acquisition
    return _gentl.DataStream_start_acquisition(self, *args)
_gentl.NoDataException: GenTL exception: Function has no data to work on. (Message from the source: Error starting buffer manager thread) (ID: -1008)
```

Interestingly, the camera works with ebus Player perfectly.

**Comment by kazunarikudo** [comment]
> Interestingly, the camera works with ebus Player perfectly.

We could assert that the issue is not on the device's GenICam XML file. eBus Player (Pleora) does not involve FLIR's GenTL Producer so the issue should not be reproduced.

As far as I see, the issue you have seen above are not identical. One is about setting a value to a feature node and the other is about a GenTL entity.

Perhaps I could guess some more if you could tell me if the PixelFormat is the only node that can reproduce the issue.
