### ISSUE TITLE
Starting image acquisition fails

### ISSUE THREAD

**Issue by CreaM129129** [genicam/harvesters#342]
**Describe the Bug**
I am trying to conect to micro-epislon surface control scanner. It is claimed scanner complies with the GenICam or GigE Vision standard. I am able to read out description out of scanner-ei. scanner is showed in _device_info_list_ and i can read trigger mode, acqisition mode and so on.
However when I try to start image acquisition I get folowing error:
`GenTL exception: Communication error, read or write to remote device failed. (Message from the source: Could not write data to 0x3ffe0004(4 bytes). No answer from device.
) (ID: -1010)`

Code:
```
from harvesters.core import Harvester
h = Harvester()
h.add_file('C:\\Program Files\\MATRIX VISION\\mvIMPACT Acquire\\bin\\x64\\mvGenTLProducer.cti')
h.update()

print(h.device_info_list)
ia = h.create()
print(ia.remote_device.node_map.AcquisitionMode.value)
ia.start()
```
If applicable, please paste the actual output (its whole traceback, etc) here:
```
[{'access_status': 1, 'display_name': 'Micro_Epsilon_Messtechnik_GmbH surfaceCONTROL_3D_3510_80(00:13:95:3b:14:03)', 'id_': 'surfaceCONTROL_3D_3510_80(00:13:95:3b:14:03)', 'model': 'surfaceCONTROL_3D_3510_80', 'parent': <genicam.gentl.Interface; proxy of <Swig Object of type 'std::shared_ptr< GenTLCpp::TLInterface > *' at 0x000001E82C719F30> >, 'serial_number': '00620060017', 'tl_type': 'GEV', 'user_defined_name': '', 'vendor': 'Micro_Epsilon_Messtechnik_GmbH', 'version': 'A01-SA05'}]
Continuous
Traceback (most recent call last):
  File "C:/Users/doirl/PycharmProjects/microEpsilon/main.py", line 9, in <module>
    ia.start()
  File "C:\Users\doirl\PycharmProjects\microEpsilon\venv\lib\site-packages\harvesters\core.py", line 2128, in start
    self.remote_device.node_map.AcquisitionStart.execute()
  File "C:\Users\doirl\PycharmProjects\microEpsilon\venv\lib\site-packages\genicam\genapi.py", line 2624, in execute
    return _genapi.ICommand_execute(self, Verify)
  File "C:\Users\doirl\PycharmProjects\microEpsilon\venv\lib\site-packages\harvesters\_private\core\port.py", line 54, in write
    self.port.write(address, value)
  File "C:\Users\doirl\PycharmProjects\microEpsilon\venv\lib\site-packages\genicam\gentl.py", line 5016, in write
    return _gentl.Port_write(self, address, buffer)
_gentl.IoException: GenTL exception: Communication error, read or write to remote device failed. (Message from the source: Could not write data to 0x3ffe0000(4 bytes). No answer from device.
) (ID: -1010)
Traceback (most recent call last):
  File "C:\Users\doirl\AppData\Local\Programs\Python\Python38\lib\weakref.py", line 642, in _exitfunc
    f()
  File "C:\Users\doirl\AppData\Local\Programs\Python\Python38\lib\weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\doirl\PycharmProjects\microEpsilon\venv\lib\site-packages\harvesters\core.py", line 1725, in destroy
    self.stop()
  File "C:\Users\doirl\PycharmProjects\microEpsilon\venv\lib\site-packages\harvesters\core.py", line 2486, in stop
    self.remote_device.node_map.AcquisitionStop.execute()
  File "C:\Users\doirl\PycharmProjects\microEpsilon\venv\lib\site-packages\genicam\genapi.py", line 2624, in execute
    return _genapi.ICommand_execute(self, Verify)
  File "C:\Users\doirl\PycharmProjects\microEpsilon\venv\lib\site-packages\harvesters\_private\core\port.py", line 54, in write
    self.port.write(address, value)
  File "C:\Users\doirl\PycharmProjects\microEpsilon\venv\lib\site-packages\genicam\gentl.py", line 5016, in write
    return _gentl.Port_write(self, address, buffer)
_gentl.IoException: GenTL exception: Communication error, read or write to remote device failed. (Message from the source: Could not write data to 0x3ffe0004(4 bytes). No answer from device.
) (ID: -1010)
Traceback (most recent call last):
  File "C:\Users\doirl\AppData\Local\Programs\Python\Python38\lib\weakref.py", line 642, in _exitfunc
    f()
  File "C:\Users\doirl\AppData\Local\Programs\Python\Python38\lib\weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\doirl\PycharmProjects\microEpsilon\venv\lib\site-packages\harvesters\core.py", line 3162, in _reset
    self._release_acquires()
  File "C:\Users\doirl\PycharmProjects\microEpsilon\venv\lib\site-packages\harvesters\core.py", line 3152, in _release_acquires
    ia.destroy()
  File "C:\Users\doirl\PycharmProjects\microEpsilon\venv\lib\site-packages\harvesters\core.py", line 1730, in destroy
    self._release_data_streams()
  File "C:\Users\doirl\PycharmProjects\microEpsilon\venv\lib\site-packages\harvesters\core.py", line 2534, in _release_data_streams
    self._release_buffers()
  File "C:\Users\doirl\PycharmProjects\microEpsilon\venv\lib\site-packages\harvesters\core.py", line 2552, in _release_buffers
    _ = data_stream.revoke_buffer(buffer)
  File "C:\Users\doirl\PycharmProjects\microEpsilon\venv\lib\site-packages\harvesters\core.py", line 214, in m
    return getattr(self._source_object, attribute)(*args)
  File "C:\Users\doirl\PycharmProjects\microEpsilon\venv\lib\site-packages\genicam\gentl.py", line 4090, in revoke_buffer
    ret = self._revoke_buffer(buffer)
  File "C:\Users\doirl\PycharmProjects\microEpsilon\venv\lib\site-packages\genicam\gentl.py", line 4095, in _revoke_buffer
    return _gentl.DataStream__revoke_buffer(self, py_obj)
_gentl.InvalidHandleException: GenTL exception: Given handle does not support the operation. (Message from the source: Invalid buffer handle(not announced)) (ID: -1006)
```
 
**Expected Behavior**
I can connect and read buffer from the scanner. 

**Configuration**

 - OS: Windows 10
 - Python: 3.8
 - Harvester: 1.3.7
 - GenTL Producer: Matrix Vision
 - Camera: Micro-Epsilon - surfaceCONTROL 3500

Thank you for assistance.

**Comment by mganglb** [comment]
Hello, 
i am facing a similar issue.

It can be resolved by calling `*.start()` twice.

best regards 
mganglb

```
from harvesters.core import Harvester
h = Harvester()
fip_cti = r"path\gevgentl\64\ids_gevgentl.cti"
h.add_file(fip_cti)
h.update()  
dev_info = h.device_info_list[0]
print(dev_info.search_keys)

ia = h.create()
try:
    ia.start()
except Exception as e:
    print("first call of start.")
    print(e)
    pass
ia.start()
print("worked on second call")
```

> first call of start.
> GenTL exception: Operation timed out before completion. (Message from the source: Writing register at remote device address 80028cb0 failed! Code: -1011. ACK status: 0.) (ID: -1011)
> worked on second call


Configuration
*  OS: Windows 10
*  Python: 3.8
