### ISSUE TITLE
1.3.3+: Crashes if _gentl.Buffer__get_tl_type is not implemented

### ISSUE THREAD

**Issue by jcormier** [genicam/harvesters#357]
**Describe the Issue**
harvesters version 1.3.3 and up crash if provider doesn't support _gentl.Buffer__get_tl_type

Traceback (most recent call last):
  File "snap.py", line 64, in <module>
    with ia.fetch_buffer(timeout=4) as buffer:
  File "C:\Users\jcormier\.conda\envs\gentl_38\lib\site-packages\harvesters\core.py", line 2347, in fetch_buffer
    return self.fetch(timeout=timeout, is_raw=is_raw, cycle_s=cycle_s)
  File "C:\Users\jcormier\.conda\envs\gentl_38\lib\site-packages\harvesters\core.py", line 2387, in fetch
    buffer = self._finalize_fetching_process(raw_buffer, is_raw)
  File "C:\Users\jcormier\.conda\envs\gentl_38\lib\site-packages\harvesters\core.py", line 2319, in _finalize_fetching_process
    self._update_chunk_data(buffer=raw_buffer)
  File "C:\Users\jcormier\.conda\envs\gentl_38\lib\site-packages\harvesters\core.py", line 2182, in _update_chunk_data
    if buffer.tl_type not in self._specialized_tl_type:
  File "C:\Users\jcormier\.conda\envs\gentl_38\lib\site-packages\genicam\gentl.py", line 4358, in _get_tl_type
    return _gentl.Buffer__get_tl_type(self)
_gentl.NotImplementedException: GenTL exception: Requested operation not implemented. (Message from the source: Function not implemented) (ID: -1003)

 
**Expected Behavior**
Expect harvesters to behave as previous if Buffer__get_tl_type is not supported.

**Configuration**

 - OS: Windows 10
 - Python: 3.7/3.8
 - Harvester: 1.3.3+
 - GenTL Producer: Critical Link 
 - Camera: Any

**Reproducibility**

This phenomenon can be stably reproduced:

- [ X] Yes
- [ ] No.

**Actions You Have Taken**

 
- [ ] I've read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).

**Additional context**

**Comment by jcormier** [comment]
Note that as of GenICAM_GenTL_1_5, BUFFER_INFO_TLTYPE is marked mandatory.  So I'll implement this for our producer, though idk why the BUFFER needs to have its own separate TLTYPE...

**Comment by jcormier** [comment]
Implemented in our producer
