### ISSUE TITLE
NodeMap import error

### ISSUE THREAD

**Issue by lmarga** [genicam/harvesters#361]
Hello.
First of all, thank you very much for harvesters product! I works great!
Unfortunately I need your help.
I had had working a software with mvGenTL_Acquire-x86_64-2.35.0, Python 3.6.8 and Harvester. 0.2.10. It had been working for more than a year.
I had to reinstall windows and after that I was not able to get harvester working again. I have done the same I had done at that PC and 3 other PCs, but I always got the same results after trying to import Harvester:

  Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
  Type "help", "copyright", "credits" or "license" for more information.
>>> import harvesters
>>> from harvesters.core import Harvester
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\15224\pytest5\lib\site-packages\harvesters\core.py", line 37, in <module>
    from genicam2.genapi import NodeMap
  File "C:\Users\15224\pytest5\lib\site-packages\genicam2\genapi.py", line 31, in <module>
    _genapi = swig_import_helper()
  File "C:\Users\15224\pytest5\lib\site-packages\genicam2\genapi.py", line 27, in swig_import_helper
    _mod = imp.load_module('_genapi', fp, pathname, description)
  File "C:\Users\15224\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\15224\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

I have installed and reinstalled several times and I have also tried python 3.8 and harvesters 1.3.8 but everytime I have gotten same results.
I believe I am missing something but I am no being able to realize what it is.
Any suggestion?
Thanks in advance.

PS: If this support request should not have been uploaded here, please, let me know where can I ask for support.

**Comment by lmarga** [comment]
Solved. There were missing the "Microsoft Visual C++ xxxx redistributable". I have installed 2013 and 2015-2022 and the issue have gone. No sure which one is needed.
Thanks.
