### ISSUE TITLE
Harvesters soft-locks when the camera gets disconnected

### ISSUE THREAD

**Issue by SkateWarp** [genicam/harvesters#371]
**Describe the Issue**
Once I initialise the module, and configure ImageAcquirer, if a disconnection happens, Harvesters stops working properly.
I saw issue #272 and #246, and there is a commit that says it solves it, but for me it does not. 

**To Reproduce**
1. Start Harvesters and ImageAcquirer normally
2. Disconnect the camera
3. doing an ia.stop() or h.reset() does nothing
4. do a h.update(), the module doesn't see any camera

**Sample Code**
 I can show a piece of code that demonstrates the reported phenomenon:

- [X] Yes
- [ ] No
- [ ] (Please select either yes or no.)

```
def camera():   
    h = harvesters.core.Harvester()    
    print(h._reset())
    h.add_file(DIR)

    print(h.update())
    if not h.device_info_list:
        print("No cameras detected")
    ia = h.create(0)
    checkconfig(ia)
    return ia,h
```

**Expected Behavior**
Reset the module to use the camera again.

**Screenshots**
![image](https://user-images.githubusercontent.com/34940433/192841168-429e39e7-e1db-46f9-8dba-eb76b89cd496.png)
h.update() returns an empty list after the exception occurs.

**Configuration**

 - OS: [Windows 10]
 - Python: [e3.10]
 - Harvester: [1.4.0]
 - GenTL Producer: [MATRIX VISION]
 - Camera: [OPTO-E COE-050-C-POE-050-IR-C]

**Reproducibility**

This phenomenon can be stably reproduced:

- [X] Yes
- [ ] No.
- [] (Please select either yes or no.)

**Actions You Have Taken**

i tried to implement the "fix" from #246, and the problem still occurs. 
The only reliable way I seen is kill and start the process again

 
- [x] I've read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).

**Additional context**
I also tried to quit the object instance by deleting any variable that makes reference to it, and "restarting" the module (with importlib), does nothing.

**Comment by SkateWarp** [comment]
Logs from Harvesters, this tracaback happens when h.update gets called after the exception:

```
MainThread: created: <harvesters.core.Harvester object at 0x00000203CB3BE740>
MainThread: being reset: <harvesters.core.Harvester object at 0x00000203CB3BE740>
MainThread: flushed file list: <harvesters.core.Harvester object at 0x00000203CB3BE740>
MainThread: discarded device information: <harvesters.core.Harvester object at 0x00000203CB3BE740>
MainThread: reset completed: <harvesters.core.Harvester object at 0x00000203CB3BE740>    
None
MainThread: added: C:\Program Files\MATRIX VISION\mvIMPACT Acquire\bin\x64\mvGenTLProducer.cti to <harvesters.core.Harvester object at 0x00000203CB3BE740>
MainThread: discarded device information: <harvesters.core.Harvester object at 0x00000203CB3BE740>
MainThread: GenTL exception: Requested resource is already in use. (Message from the source: ) (ID: -1004)
Traceback (most recent call last):
  File "c:\Users\Desarrollo-00\Desktop\threadpoolexample.py", line 81, in imageprocessing    ia.start()
  File "C:\Users\Desarrollo-00\AppData\Roaming\Python\Python310\site-packages\harvesters\core.py", line 2131, in start
    self.remote_device.node_map.AcquisitionStart.execute()
  File "C:\Users\Desarrollo-00\AppData\Roaming\Python\Python310\site-packages\genicam\genapi.py", line 2439, in execute
    return _genapi.ICommand_execute(self, Verify)
  File "C:\Users\Desarrollo-00\AppData\Roaming\Python\Python310\site-packages\harvesters\_private\core\port.py", line 54, in write
    self.port.write(address, value)
  File "C:\Users\Desarrollo-00\AppData\Roaming\Python\Python310\site-packages\genicam\gentl.py", line 4560, in write
    return _gentl.Port_write(self, address, buffer)
_gentl.AccessDeniedException: GenTL exception: Requested operation is not allowed. (Message from the source: No write access to device COE-050-C-POE-050-IR-C(MAC)(current access DEVICE_ACCESS_STATUS_OPEN_READONLY)) (ID: -1005)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Desarrollo-00\AppData\Roaming\Python\Python310\site-packages\harvesters\core.py", line 3142, in _open_gentl_producers
    raw_producer.open(file_path)
  File "C:\Users\Desarrollo-00\AppData\Roaming\Python\Python310\site-packages\genicam\gentl.py", line 2073, in open
    return _gentl.GenTLProducer_open(self, path_name)
_gentl.ResourceInUseException: GenTL exception: Requested resource is already in use. (Message from the source: ) (ID: -1004)
```

**Comment by kazunarikudo** [comment]
@SkateWarp Hi, thank you for trying out Harvester and for the report. As of today, Harvester does not have involved any mechanism to react to disconnection even though I understand disconnection can happen in real applications. I would like to address the issue but I need to tell you the solution would not show up soon. I will officially inform all of you if the feature is supported in the end. Regards, Kazunari.

**Comment by MathijsNL** [comment]
For me it seems to be working to do the following after a disconnect (plugging out and plugging in the network cable):

```
ia.destroy()
h.update()
ia = h.create()
```

Can you try the ia.destroy() before trying to initialize again? If it is not working can you share a working code snippet that I can run to reproduce the issue?

**Comment by SkateWarp** [comment]
> For me it seems to be working to do the following after a disconnect (plugging out and plugging in the network cable):
> 
> ```
> ia.destroy()
> h.update()
> ia = h.create()
> ```
> 
> Can you try the ia.destroy() before trying to initialize again? If it is not working can you share a working code snippet that I can run to reproduce the issue?

I'll send a more detailed snippet of the code today, or if not, in Tuesday (university exams and deadlines are keeping me busy).

But basically, if you have an instance of `ia` initialized, and connected to a camera; and the camera suddenly disconnects and you use `ia.start`, the module will soft-lock.

**Comment by jcormier** [comment]
If this is a usb camera, atleast for our gentle plugin we have found that libusb doesn't handle sudden USB disconnects without crashing.  Would love if anybody knows a way around this.

**Comment by croclivre** [comment]
Is there any update on that issue.
I captured images on a remote PC, if I unplug the camera physicaly, it waits for reconnection and it doesn't softlock itself.
If there's a reboot on the remote desktop, it softlock itself even if ia.destroy() has been executed.

Whenever it's softlock itself my camera isn't anymore in DHCP on my software.
