### ISSUE TITLE
1.4.2: Buffer used is too small for operation when calling create(0)

### ISSUE THREAD

**Issue by jcormier** [genicam/harvesters#409]
**Describe the Issue**

When moving from 1.4.0 to 1.4.2, the create function throws an exception.  

**To Reproduce**

pip install harvesters==1.4.2 genicam==1.2.0
python snap.py

**Sample Code**
 I can show a piece of code that demonstrates the reported phenomenon:

- [x ] Yes
- [ ] No

If yes, please provide a sample code:
```
h = Harvester(logger=logger, do_clean_up=False)
h.add_file('c:\\Program Files\\Critical Link LLC\\GenTL Viewer\\bin\\GenTL.dll')
h.update()
ia = h.create(0)
```
If applicable, please paste the actual output (its whole traceback, etc) here:
```
```
Traceback (most recent call last):
  File "snap.py", line 81, in <module>
    ia = h.create(0)
  File "C:\Users\jcormier\.conda\envs\gentl_38\lib\site-packages\harvesters\core.py", line 3082, in create
    return self._create_acquirer(device_proxy=device_proxy, config=config)
  File "C:\Users\jcormier\.conda\envs\gentl_38\lib\site-packages\harvesters\core.py", line 3112, in _create_acquirer
    ia = ImageAcquirer(device_proxy=device_proxy_, config=config,
    manager(module.register_event(event_type))
  File "C:\Users\jcormier\.conda\envs\gentl_38\lib\site-packages\harvesters\core.py", line 228, in m
    return getattr(self._source_object, attribute)(*args)
  File "C:\Users\jcormier\.conda\envs\gentl_38\lib\site-packages\genicam\gentl.py", line 2303, in register_event
    return _gentl.System_register_event(self, event_id)
_gentl.BufferTooSmallException: GenTL exception: Buffer used is too small for operation. (Message from the source: Buffer was too small)
```
 
**Expected Behavior**
A clear and concise description of what you expected to happen.

1.4.0 works just fine.  Trying to figure out what changed in 1.4.2 and get more info on what might be missing or broken in our producer.  But the error message is a bit vague

**Screenshots**

![image](https://user-images.githubusercontent.com/5613721/231803537-d3083972-ee7a-4eb6-9557-352d022c4556.png)

**Configuration**


 - OS: Windows 10
 - Python: 3.8
 - Harvester: 1.4.2
 - GenTL Producer: CriticalLink
 - Camera: SimCamera

**Reproducibility**

This phenomenon can be stably reproduced:

- [x ] Yes
- [ ] No.

If applicable, please provide your observation about the reproducibility.

**Actions You Have Taken**

Happens anytime I switch to 1.4.2 and goes away when switching back to 1.4.0
 
- [ x] I've read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).

**Additional context**
Add any other context about the problem here.

**Comment by jack77er** [comment]
I can confirm this bug in 1.4.2, Python 3.10

>  Traceback (most recent call last):
>   File "M:\Software\GUI\main.py", line 833, in changeScannerPixelFormat
>     self.scanner.scanner.start()
>   File "C:\Dev\Python3_10\lib\site-packages\harvesters\core.py", line 2256, in start
>     ds.start_acquisition(
>   File "C:\Dev\Python3_10\lib\site-packages\harvesters\core.py", line 228, in m
>     return getattr(self._source_object, attribute)(*args)
>   File "C:\Dev\Python3_10\lib\site-packages\genicam\gentl.py", line 3454, in start_acquisition
>     return _gentl.DataStream_start_acquisition(self, *args)
> _gentl.BufferTooSmallException: GenTL exception: Buffer used is too small for operation. (Message from the source: StartAcquisition: one or more of the announced buffers are smaller than required) (ID: -1016)

The exception in thrown when I change the pixel format of my device (it's a laser scanner with genicam interface) for example from Mono8 to Mono12 or similar. I'm doing this by setting a node value of the remote device NodeMap.
