### ISSUE TITLE
HikRobot cti file (MVS)

### ISSUE THREAD

**Issue by abogadi** [genicam/harvesters#442]
**Describe the Issue**
Harvesters raises LogicalErrorException  when trying to use HikRobot cti file.
I would like to understand if this is a Hikrobot driver issue   or something that can be resolved in Harvesters.
I am keen to help resolve this issue, if further or specific tests are needed please let me know!

**To Reproduce**
Se sample code below

**Sample Code**
 I can show a piece of code that demonstrates the reported phenomenon:

- [X] Yes
- [ ] No
- [] (Please select either yes or no.)

If yes, please provide a sample code:
```
from harvesters.core import Harvester
import sys
import traceback
import cv2
import time

def main():
    h = Harvester()
    h.add_file("C:\\Program Files (x86)\\Common Files\\MVS\\Runtime\\Win64_x64\\MvProducerGEV.cti") 
    h.update()
    time.sleep(1)
    print(len(h.device_info_list))
    for onedevice in h.device_info_list:
        print(onedevice)
        print('next')
    ia = h.create(0)
    #ia.device.node_map.PixelFormat.value = 'BayerRG8'
    #ia.device.node_map.TestPattern = 'HorizontalColorBar'
    try:
        ia.start()
        i = 0
        done = False
        while not done:
            with ia.fetch() as buffer:
                img = buffer.payload.components[0].data
                img = img.reshape(buffer.payload.components[0].height, buffer.payload.components[0].width,3)
                img_copy = img.copy()
                img_copy = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
                cv2.namedWindow("window", cv2.WINDOW_KEEPRATIO | cv2.WINDOW_NORMAL)
                cv2.imshow("window", img_copy)
                fps = ia.statistics.fps
                print("FPS: ", fps)
                if cv2.waitKey(10) == ord('q'):
                    done = True
                    print('break')
                i = i + 1
    except Exception as e:
        traceback.print_exc(file=sys.stdout)
    finally:
        ia.stop()
        ia.destroy()
        cv2.destroyAllWindows()
        print('finally')
        h.reset()

if __name__ == "__main__":
    main()

```
If applicable, please paste the actual output (its whole traceback, etc) here:
```
E:\vis\newvenv310\Scripts\python.exe E:\vis\harvester.py 
Traceback (most recent call last):
  File "E:\vis\harvester.py", line 62, in <module>
    main()
  File "E:\vis\harvester.py", line 24, in main
    h.update()
  File "E:\vis\newvenv310\lib\site-packages\harvesters\core.py", line 3446, in update
    self._open_systems()
  File "E:\vis\newvenv310\lib\site-packages\harvesters\core.py", line 3341, in _open_systems
    self._systems.append(System(module=raw_system, parent=producer))
  File "E:\vis\newvenv310\lib\site-packages\harvesters\core.py", line 515, in __init__
    super().__init__(module=module, parent=parent, port=module.port)
  File "E:\vis\newvenv310\lib\site-packages\harvesters\core.py", line 281, in __init__
    self._node_map = self._create_node_map(
  File "E:\vis\newvenv310\lib\site-packages\harvesters\core.py", line 320, in _create_node_map
    clean_up_required, file_path = self._retrieve_file_path(
  File "E:\vis\newvenv310\lib\site-packages\harvesters\core.py", line 378, in _retrieve_file_path
    raise LogicalErrorException(
_genapi.LogicalErrorException: The target port does not hold any URL.

Process finished with exit code 1
```
 
**Expected Behavior**
Open camera and acquire images

**Screenshots**

**Configuration**

 - OS: Windows x64
 - Python: 3.10
 - Harvester: 1.4.2
 - GenTL Producer: MVS 64bit V4.3.0 build 20231124 (C:\Program Files (x86)\Common Files\MVS\Runtime\Win64_x64\MvProducerGEV.cti)
 - Camera: HikRobot MV-CA050-12GC

**Reproducibility**

This phenomenon can be stably reproduced:

- [X] Yes
- [ ] No.
- [] (Please select either yes or no.)

If applicable, please provide your observation about the reproducibility.

**Actions You Have Taken**

 
- [ ] I've read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).

**Additional context**

**Comment by abogadi** [comment]
No, I am still waiting to hear back from Hikrobot on the same topic

**Comment by ardainanc** [comment]
Hi again. I found a temporary solution for our case. I used mvGenTL_Acquire as it doesn't block the other producers products. You can find the relevent info here: https://harvesters.readthedocs.io/en/latest/INSTALL.html#installing-a-gentl-producer . This worked with my mv-cs060 gige camera. It would also be great if you can notify me when you here back from Hikrobot on their own .cti file.

**Comment by mbsoysal** [comment]
Hi. I am having the same issue. It's been 7 months since the issue was opened and the cti file provided by Hikrobot still causes LogicalErrorException with Harvesters. Did anyone figure out a solution/workaround?

**Comment by TEXflip** [comment]
Hi, I have the same issue but I found a hint on why it doesn't work. The error is raised because inside the .cti file is missing the feature tree that every GenTL producer should have.
In the Hikrobot's SDK there are several .cti files, in my case with SDK version 4.1.1.2 I have the following files:
- ./lib/32/MvProducerGEV.cti
- ./lib/32/MvProducerU3V.cti
- ./lib/64/MvFGProducerXoF.cti
- ./lib/64/MvFGProducerCXP.cti
- ./lib/64/MvFGProducerCML.cti
- ./lib/64/MvFGProducerGEV.cti
- ./lib/64/MvProducerGEV.cti
- ./lib/64/MvProducerU3V.cti

I found that the last 2 are the ones which I got the error, instead the others they don't raise any exception but they don't see any camera. I strongly suspect that the missing feature tree is written inside all the "FG" producers beacuse they are larger files (~600kB instead of ~70kB) and "FG" it probably means "Feature Graph".

So I think it's possible to have a working .cti file by editing them and importing the feature tree from the FG files to the non-FG ones, but unfortunately I didn't found how to read this format yet.

**Comment by ma-mehralian** [comment]
ON WINDOWS:
`.cti` files are sort of shared libraries (i.e. DLL in windows). It has dependency to the other DLLs. Adding all `MVS_SDK_Runtime` DLLs to my windows path it works for me! (these files *_VC120_v3_0_MV.dll +  MvRender + MvUsb3vTL + libusb0 + MvCameraControl)

**Comment by TEXflip** [comment]
I contacted hikrobot and I finally managed to make it work in Ubuntu with this environment:
- MVS SDK version: 4.5
- OS: Ubuntu 22.04, Linux 6.8.0-52-generic
- python: 3.10.16
- harvesters: 1.4.3
- opencv: 4.9.0

And this code:

```python
import cv2
from harvesters.core import Harvester, Component2DImage

h = Harvester()
h.add_file("/opt/MVS/lib/64/MvProducerGEV.cti", True, True)
h.update()
ia = h.create(0)
ia.remote_device.node_map.ExposureTime.set_value(10000)
ia.start()
cv2.namedWindow("test", cv2.WINDOW_NORMAL)
cv2.resizeWindow("test", 800, 800)

while True:
    with ia.fetch() as buffer:
        img: Component2DImage = buffer.payload.components[0]
        npimg = img.represent_pixel_location()
        npimg = cv2.cvtColor(npimg, cv2.COLOR_BAYER_BG2BGR)
        cv2.imshow("test", npimg)
        key = cv2.pollKey()
        if key == 27 or cv2.getWindowProperty("test", cv2.WND_PROP_VISIBLE) < 1:
            break
ia.stop()
ia.destroy()
```

Also make sure that the `Device User ID` doesn't have Chinese or non-unicode characters

For some reason it doesn't work with python3.11 beacuse I keep getting random `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 80: invalid start byte` and I didn't tested on other versions. But I'm happy that at least it works on 3.10.

**Comment by abogadi** [comment]
Seems like it works on both Linux and Windows, the issue is now closed

**Comment by matejnevlud** [comment]
I can confirm that using (Hik-Robot) MVS SDK GenTL Producer works on jetson orin nano with Ubuntu and can successfully grab frames from Cognex CIC GigE 2MP camera (manufactured by iRAYPLE).
