### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by IlyaHalsky** [genicam/harvesters#472]
**What is the goal that you want to achieve by the request?**
Python 3.12 came out on October 2, 2023, by default Ubuntu 24.04 now comes with Python 3.12. It would be nice to implement support for it.

**Additional context**
To my understanding from #422 the only thing holding back is genicam package, but I might be wrong.

**Comment by builder26** [comment]
I have a large project, depending on Harvesters and it's been a pain that there's no support for 3.12. We will be switching to other methods when we can, to avoid Harvesters.

**Comment by matthijsgeers-keysight** [comment]
I'd like to second this. I tried to get in touch with the maintainer of the genicam package at the maintainer e-mail address (genicam@list.stemmer-imaging.com), which seems to be the same address as the one for harvesters. However, the address is no longer in use. I've asked the owners of the domain about this address, but they don't seem to have any knowledge of it. Is @kazunarikudo still around? They seem to be the sole person responsible for both genicam and harvesters

**Comment by sunavlis** [comment]
Hi @matthijsgeers-keysight Thanks for the hint that the e-mail adress is not working anymore.

I will check to update to an actual one.

About the Python 3.12 release: We are working on the release and I would expect to have the tested binaries ready on approx. 1 month. 

Actually we are working on a new build infrastructure where future updates would be available much faster. I have to say sorry that it take so long for this 3.12 release. It would be much better in the future, I promise it.

**Comment by TTMaDe** [comment]
I asked a genicam developer some weeks ago and he said a new genicam release is in the making and Python 3.12 support will be included but there was no timeline yet.

**Comment by matthijsgeers-keysight** [comment]
Hey @sunavlis , thank you for your insanely fast reply. Since only one person is listed as a member of the genicam organization on GitHub, it appears as if only they are working on these projects. It's good to hear the bus factor is being accounted for :)

Good news about the upcoming release! I was wondering, while you're at it, would it make sense to also include a release for Python 3.13? This was officially released last month (see https://devguide.python.org/versions/)

**Comment by sunavlis** [comment]
Ow, I just realized that we can manage who are public visible behind the "GenICam organization" on github. Right now, I configured me also as public member of the organization. 

I can say, we are a bigger group working on the standard. I spend time to refactoring the whole python build infrastructure (of the genicam package). This allows as to create releases more efficient and faster...


Ans yes, we try to build python 3.13 as well. Since the release which I spoke is still on the old infrastructure which uses a few features depreciated in python 3.13 I'm not sure if we will finalize it. If the fixes small, than of course.

**Comment by psous32** [comment]
One question.!
Is the harvester and genicam compatible with python 3.11?

**Comment by Inkaros** [comment]
@paulosousa32 
It is, we are using 3.11 while waiting for 3.12/3.13 support.

**Comment by psous32** [comment]
Ok, nice ! Because I'm having problems fetching the return buffer, which is always empty, and it could be due to my version of python.

**Comment by TTMaDe** [comment]
Thanks for your work @sunavlis! Is there any news regarding Python 3.12 support or an approximate release date?

**Comment by qrmt** [comment]
Is there any news on this @sunavlis?

**Comment by sunavlis** [comment]
It seams that the internal voting and release time takes a bit longer than expected by my self...
But there is a "release candidate" available which I just uploaded to TestPyPi. You can install it with the command:
`pip install -i https://test.pypi.org/simple/ genicam==1.5.0`

Please let me know, if you observe any issues. As soon as, the internal release procedure for the whole GenICam reference implementation is done, I would upload it to PyPi as well. I would expect, that this could be done until the end of April 2025.

I hope, you are able to use Python 3.12 and 3.13 in the meantime based on the genicam package from Test PyPi. (The Harvesters package from PyPi works together with genicam 1.5.0.)

I will inform here again, as soon as the release is available on PyPi too. Thanks for you patient.

**Comment by RockHeroGit** [comment]
In Python 3.12 with genicam==1.5.0 i have error :

`Traceback (most recent call last):
  File "c:\Work\programming\python\tests\camera.py", line 13, in <module>
    ia = h.create()
         ^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\harvesters\core.py", line 3088, in create
    return self._create_acquirer(device_proxy=device_proxy, config=config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\harvesters\core.py", line 3118, in _create_acquirer
    ia = ImageAcquirer(device_proxy=device_proxy_, config=config,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\harvesters\core.py", line 1665, in __init__
    manager(module.register_event(event_type))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\harvesters\core.py", line 228, in m
    return getattr(self._source_object, attribute)(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\genicam\gentl.py", line 2303, in register_event
    return _gentl.System_register_event(self, event_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 80: invalid start byte`

**Comment by Inkaros** [comment]
Any updates on Python 3.12+ support @sunavlis ? Not sure if it is tied to EMVA meeting schedule or 3.14 release cycle and trying to anticipate when this might happen.

**Comment by sunavlis** [comment]
Hi @Inkaros  I just uploaded 3.12 and 3.13. So you should be able to use genicam 1.5.0 and Harvesters now on this two versions.

Thanks to everyone for the patience!

If you observe any issue, please let me know.
