### ISSUE TITLE
Harvester.update() breaks existing camera connections

### ISSUE THREAD

**Issue by MYCL94** [genicam/harvesters#475]
**Describe the Issue**

The existing connection to my camera gets broken when using `harvester.update()` to check for newly connected devices. 

**To Reproduce**

1. My application uses `harvester.update()` to check every 10 seconds if a new device has been connected.
2. The existing connection to my camera gets broken when using `harvester.update()`.

**Sample Code**
```python
h = Harvester()
while True:
    h.update()
    time.sleep(10)
```
If applicable, please paste the actual output (its whole traceback, etc) here:

```
 :: harvesters.core :: ERROR :: GenTL exception: Given handle does not support the operation. (Message from the source: Unsupported info parameter) (ID: -1006)
Traceback (most recent call last):
  File "\venv\lib\site-packages\harvesters\core.py", line 2435, in _fetch
    monitor.update_event_data(self.timeout_period_on_update_event_data_call)
  File "\venv\lib\site-packages\genicam\gentl.py", line 1296, in update_event_data
    return _gentl.EventManagerNewBuffer_update_event_data(self, timeout)
_gentl.InvalidHandleException: GenTL exception: Given handle does not support the operation. (Message from the source: Unsupported info parameter)
```

**Expected Behavior**

I expect that `harvester.update()` will only update the device_info_list and not break existing connections to devices like my camera.

As I understood the `harvester.update()` method description already mentions this might happen, which is why I am not sure if this shouldn't have been a feature request.

**Screenshots**
None

**Configuration**

- OS: Windows 10
- Python: 3.10.8
- Harvester: 1.4.2
- GenTL Producer: libbgapi 2.13.2
- Camera: Baumer VCXG-25M.I.XT &  VCXG.2-51M

**Reproducibility**

This phenomenon can be stably reproduced.

**Actions You Have Taken**

I have created my own broadcasting service to be able to check if a new camera has been connected, which is working now but I am not able to connect since the `harvester.update()` has to be done in the final step. 
I tried to create multiple harvester objects but as mentioned here (https://github.com/genicam/harvesters/issues/344) this is not the way to use it. I also tried broadcasting services, which is working now.
I also tried to comment each of the release() in the harvester.update() method
```
def update(self) -> None:
        """
        ...
        Please note that the update method call will eventually turn the
        existing ImageAcquire objects immediately obsolete even if the object
        is still owned by someone. The owner should drop those obsolete
        objects and create another ImageAcquisition object by calling
        the Harvester.create_image_acquire method.
        """
        global _logger

        #self._release_acquires()
        #self._release_gentl_producers()

        try:
```

But this is going to result in the error:
```
_gentl.ResourceInUseException: GenTL exception: Requested resource is already in use. (Message from the source: ) (ID: -1004)```
```

**Additional Context**

I really hope to find at least a workaround to be able to continue using harvesters. 
Thank you for your help! 

Update:
I did try the same with harvesters 1.4.3 and this resulted in a different behavior:
For a basic test I tried it with a single camera. First connected to the camera and then unplugged it. After ia.destroy() in my error handling I tried to do
harvester.update(), which results in the error message below. With a single camera this was working on 1.4.2 for a basic error recovery. 

`self._harvester.update()
  File "\venv\lib\site-packages\harvesters\core.py", line 3447, in update
    self._release_acquires()
  File "\venv\lib\site-packages\harvesters\core.py", line 3352, in _release_acquires
    ia.destroy()
  File "\venv\lib\site-packages\harvesters\core.py", line 1877, in destroy
    self._release_data_streams()
  File "\venv\lib\site-packages\harvesters\core.py", line 2720, in _release_data_streams
    self._release_buffers()
  File "\venv\lib\site-packages\harvesters\core.py", line 2739, in _release_buffers
    _ = data_stream.revoke_buffer(buffer)
    return getattr(self._source_object, attribute)(*args)
  File "\venv\lib\site-packages\genicam\gentl.py", line 3690, in revoke_buffer
  File "\venv\lib\site-packages\genicam\gentl.py", line 3695, in _revoke_buffer
    return _gentl.DataStream__revoke_buffer(self, py_obj)
_gentl.BusyException: GenTL exception: Operation cannot be performed. Responsible module is busy. (Message from the source: The buffercount must not change while acquisition is active!) (ID: -1022)`

**Comment by MYCL94** [comment]
I'm glad I was able to find a solution that works for me. However, I still hope to see this feature included in a future main release. The changes can be found here.

https://github.com/MYCL94/harvesters/tree/feature/update-device-list-without-release

```
def update(self) -> None:
        global _logger
        
        try:
            self._open_gentl_producers()
            self._open_systems()
            for system_proxy in self._systems:
                system_proxy.update_interface_info_list(self.timeout_for_update)

                for i_info in system_proxy.interface_info_list:
                    try:
                        if i_info.id_ not in self._i_info_id:
                            raw_iface = i_info.create_interface()
                            self._i_info_id.append(i_info.id_)
                            self._raw_ifaces.append(raw_iface)
                            raw_iface.open()
                            _logger.debug('opened: {0}'.format(_family_tree(raw_iface)))
                            iface_ = Interface(module=raw_iface, parent=system_proxy)
                            if iface_ not in self._ifaces:
                                self._ifaces.append(iface_)
                    except GenTL_GenericException as e:
                        _logger.error(e, exc_info=True)       
                self._device_info_list = []
                for raw_iface, iface_ in zip(self._raw_ifaces, self._ifaces):
                    raw_iface.update_device_info_list(self.timeout_for_update)
                    for dev_info in raw_iface.device_info_list:
                        self.device_info_list.append(
                                DeviceInfo(module=dev_info, parent=iface_))

        except GenTL_GenericException as e:
            _logger.warning(e, exc_info=True)
            self._has_revised_device_list = False
        else:
            self._has_revised_device_list = True

        _logger.info('updated: {}'.format(self))
```
I also had to introduce new lists to check for already opened interfaces. This makes it possible to continuously use harvester.update() without losing the (working) ImageAcquirers. If a new device is attached, it is also found and connected by checking the device_info_list before harvester.create(). I wasn't sure if I should have created a new method for that, but for now I changed the update() method since it's fine in my use case. I don't add or remove interfaces, and I'm just using the one cti Producer mentioned above; which is why I don't see why I should release the GenTL Producer at all. This change also worked with harvesters 1.4.3.
Thanks!

**Comment by OliverMeierVolpi** [comment]
Hi All

Any progress on this?
This PR seems very handy and it is open without any reply since over a year now. Is harvesters still being maintained?
I would be willing to test this with some genicam cameras I have available, also in parallel..

Thanks for any sign of life :)

**Comment by MYCL94** [comment]
Hi Oliver,

I am actively using my own fork now, since updates and feedback take very long. We are also relying on this library, and I would love to see this in the main repo, so I don't have to keep track of two different repositories. We haven’t had issues so far with this change, tested with Baumer, TIS, and others like Hikvision. 

I had many ideas in the last few weeks to refactor, but this would lead to a bigger gap with the main repo, making me stand still. 

Regards
