### ISSUE TITLE
SyntaxError is raised when harvester is imported.

### ISSUE THREAD

**Issue by kazunarikudo** [genicam/harvesters#64]
**Describe the bug**
SyntaxError is raised when harvester is imported.

**To Reproduce**
1. Import `harvester` in a script. 
2. Run the script.
3. You'll see the following traceback.

`
Traceback (most recent call last):
  File "harvester_test.py", line 2, in <module>
    from harvesters.core import Harvester
  File "python-3.5.4-embed-amd64\lib\site-packages\harvesters\core.py", line 1239
    ):
    ^
SyntaxError: invalid syntax
`

**Expected behavior**
Any exceptin must not be raised while `harvester` is being imported.

**Additional context**
None.

**Comment by kazunarikudo** [comment]
The bug has been introduced at `0.2.3`.

**Comment by kazunarikudo** [comment]
It's been fixed at 57cbb0225119d1a4a1055a65f7b8578ddc680af4.
