### ISSUE TITLE
GenTL exception in fetch_buffer() with JAI GO-5000C-USB Camera

### ISSUE THREAD

**Issue by MarkR80** [genicam/harvesters#75]
**Describe the bug**
I am trying to acquire an image with a JAI GO-5000C-USB camera. Calling fetch_buffer() generates a GenTL exception:
`Requested operation not implemented. (Message from the source: GetBufferInfo: padding_y not expected within USB3 Vision streaming protocol) (ID: -1003)`

**To Reproduce**
```
from harvesters.core import Harvester
h = Harvester()
h.add_cti_file(r'C:\Program Files\JAI\SDK\bin\JaiUSB3vTL.cti')
h.update_device_info_list()
print('Devices:\n', h.device_info_list)
camera = h.create_image_acquirer(0)
camera.device.node_map.PixelFormat.value = 'BayerGR8'
camera.start_image_acquisition()
buffer = camera.fetch_buffer()
```

Output:
```
Devices:
 [(id_='14FB00B7A485_JAILtdJapan_GO5000CUSB', vendor='JAI Ltd., Japan', model='GO-5000C-USB', tl_type='U3V', user_defined_name=None, serial_number='U500869', version='0.1.0.8')]
Traceback (most recent call last):

  File "<ipython-input-1-8dd3a92afe7e>", line 1, in <module>
    runfile('C:/Users/xxx/Test_image_acq.py', wdir='C:/Users/xxx')

  File "C:\Users\xxx\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "C:\Users\xxx\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/xxx/Test_image_acq.py", line 22, in <module>
    buffer = camera.fetch_buffer()

  File "C:\Users\xxx\AppData\Local\Continuum\anaconda3\lib\site-packages\harvesters\core.py", line 1806, in fetch_buffer
    logger=self._logger

  File "C:\Users\xxx\AppData\Local\Continuum\anaconda3\lib\site-packages\harvesters\core.py", line 779, in __init__
    logger=self._logger

  File "C:\Users\xxx\AppData\Local\Continuum\anaconda3\lib\site-packages\harvesters\core.py", line 901, in _build_payload
    buffer=buffer, node_map=node_map, logger=logger

  File "C:\Users\xxx\AppData\Local\Continuum\anaconda3\lib\site-packages\harvesters\core.py", line 1040, in __init__
    buffer=buffer, node_map=node_map

  File "C:\Users\xxx\AppData\Local\Continuum\anaconda3\lib\site-packages\harvesters\core.py", line 978, in _build_component
    return Component2DImage(buffer=buffer, part=part, node_map=node_map)

  File "C:\Users\xxx\AppData\Local\Continuum\anaconda3\lib\site-packages\harvesters\core.py", line 579, in __init__
    count += self.y_padding

  File "C:\Users\xxx\AppData\Local\Continuum\anaconda3\lib\site-packages\harvesters\core.py", line 740, in y_padding
    value = self._buffer.padding_y

  File "C:\Users\xxx\AppData\Local\Continuum\anaconda3\lib\site-packages\genicam2\gentl.py", line 4310, in _get_padding_y
    return _gentl.Buffer__get_padding_y(self)

NotImplementedException: GenTL exception: Requested operation not implemented. (Message from the source: GetBufferInfo: padding_y not expected within USB3 Vision streaming protocol) (ID: -1003)
```

**Expected behavior**
The code should acquire an image. The camera works as expected in the JAI Control Tool and Matlab R2018a.

**Desktop (please complete the following information):**
 - OS: Windows 7 with the Anaconda distribution
```
Python 3.6.7 |Anaconda, Inc.| (default, Dec 10 2018, 20:35:02) [MSC v.1915 64 bit (AMD64)]
JAI SDK 3.0.7
```

**Comment by MarkR80** [comment]
Is there a quick workaround to disable padding? `fetch_buffer(is_raw=True)` does not generate an error, but I don't know how to extract the image data.

**Comment by kazunarikudo** [comment]
I have just pushed the bug fix to the repository. Could you try that out, please? Note that passing `is_raw=True` will just give you a raw content and any dissection will not be done by Harvester. It would make sense in a debugging situation but not for any practical situation. -Kazunari

**Comment by MarkR80** [comment]
The bug fix resolves the GenTL exception in `fetch_buffer`. Thank you!

**Comment by kazunarikudo** [comment]
Glad to hear that. Thank you again for getting interested in Harvester! -Kazunari

**Comment by littlecong** [comment]
The same code on my machine  complains

GenTL producer does not implement DSGetNumBufferParts
GenTL producer does not implement DSGetBufferPartInfo

any suggestion?

OS: Windows 7
Python 3.6.3 |Anaconda, Inc.
JAI SDK 3.0.7
harvesters-0.2.10
